---
title: "distributions"
author: "Stephane Mertens de Wilmars"
date: "20-5-2021"
output: html_document
---

Demonstration that xi = lambda + 1
```{r}
require(fitdistrplus)
require(sgt)



par(mfrow=c(2,2))
xvals = seq(-3,3,by=0.01)
plot(xvals, dsstd(xvals, mean = 0, sd = 1.48, xi = 0.01, nu = 3.37), col="red", type ="l", main = "xi=0 (ST)", ylab="Density")
#lines(xvals, dsstd(xvals, mean = 0.02, sd = 1.48, xi = 0.80, nu = 3.37), col="blue", type ="l", main = "T", ylab="Density")
#lines(xvals, dsstd(xvals, mean = 0.02, sd = 1.48, xi = 0.24, nu = 3.37), col="yellow", type ="l", main = "T", ylab="Density")
abline(v=0)

plot(xvals, dsgt(xvals, mu = 0, sigma = 1.3, lambda = -0.99, p = 1.38,q=3.3), col="red", type ="l", main = "Lambda = -1 (SGT)", ylab="Density")
#lines(xvals, dsgt(xvals, mu = 0.02, sigma = 1.3, lambda = -0.2, p = 1.38,q=3.3), col="blue", type ="l")
#lines(xvals, dsgt(xvals, mu = 0.02, sigma = 1.3, lambda = -0.76, p = 1.38,q=3.3), col="yellow", type ="l")
abline(v=0)


plot(xvals, dsstd(xvals, mean = 0, sd = 1.48, xi = 1, nu = 3.37), col="red", type ="l", main = "xi=1 (ST)", ylab="Density")
#lines(xvals, dsstd(xvals, mean = 0.02, sd = 1.48, xi = 0.80, nu = 3.37), col="blue", type ="l", main = "T", ylab="Density")
#lines(xvals, dsstd(xvals, mean = 0.02, sd = 1.48, xi = 0.24, nu = 3.37), col="yellow", type ="l", main = "T", ylab="Density")
abline(v=0)

plot(xvals, dsgt(xvals, mu = 0, sigma = 1.3, lambda = 0, p = 1.38,q=3.3), col="red", type ="l", main = "Lambda = -1 (SGT)", ylab="Density")
#lines(xvals, dsgt(xvals, mu = 0.02, sigma = 1.3, lambda = -0.2, p = 1.38,q=3.3), col="blue", type ="l")
#lines(xvals, dsgt(xvals, mu = 0.02, sigma = 1.3, lambda = -0.76, p = 1.38,q=3.3), col="yellow", type ="l")
abline(v=0)
```

In Bali, $\eta$ is the tail-thickness parameter & $\kappa$ the peakedness parameter. In SGT package, $p = \kappa$ and $q = \eta$

```{r}
xvals = seq(-3,3,by=0.01)

#allowing p to vary


plot(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = -0.5, p = 1.38,q=3.3), col="red", type ="l", main = "Allowing p to vary (SGT)", ylab="Density",ylim = c(0,1))
lines(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = -0.5, p = 1.2,q=3.3), col="blue", type ="l", main = "SGT function", ylab="Density")
lines(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = -0.5, p = 0.9,q=3.3), col="black", type ="l", main = "SGT function", ylab="Density")

#allowing q to vary

plot(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = -0.5, p = 1.38,q=3.3), col="red", type ="l", main = "Allowing q to vary (SGT)", ylab="Density")
lines(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = -0.5, p = 1.38,q=3), col="blue", type ="l", main = "SGT function", ylab="Density")
lines(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = -0.5, p = 1.38,q=2.5), col="black", type ="l", main = "SGT function", ylab="Density")


#normal distribution & SGT ( constrained to normaldist)

plot(xvals, dnorm(xvals, mean = 0, sd = 1), col="red", type ="l", main = "Normaldist & SGT with p=2, q=Inf", ylab="Density",ylim = c(0,1))
lines(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = 0, p = 2,q=Inf), col="blue", type ="p")
?sstd






```

Is $\nu$ equal to $\eta$?
```{r}
plot(xvals, dsstd(xvals, mean = 0, sd = 1.3, xi = 1, nu = 3.37), col="red", type ="l", main = "ST(fistdist with nu=3.37) & ST(sgt with p=2, q=3.37)", ylab="Density")
lines(xvals, dsgt(xvals, mu = 0, sigma = 1.3, lambda = 0, p = 2,q=3.37), col="blue", type ="l", main = "", ylab="Density")
```




What is the connection between $\nu$ and $p$ & $q$?

```{r}
p <- 2 #constrained under st
q <- 2
lambda <- -0.06


plot(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = lambda, p = p,q=q), col="red", type ="p", main = "ST(sgt) & ST(fitdist), nu=p*q, p=2, lambda=-0.06", ylab="Density",ylim=c(0,0.8))

lines(xvals, dsstd(xvals, mean = 0, sd = 1, xi = (lambda+1), nu = p*q), col="blue", type ="l", main = "ST", ylab="Density")
abline(v=0)

plot(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = 0.5, p = p,q=q), col="red", type ="p", main = "ST(sgt) & ST(fitdist), nu=p*q, p=2, lambda=0.5", ylab="Density",ylim=c(0,0.8))

lines(xvals, dsstd(xvals, mean = 0, sd = 1, xi = 1.5, nu = p*q), col="blue", type ="l", main = "ST", ylab="Density")

plot(xvals, dsgt(xvals, mu = 0, sigma = 1, lambda = 0.9, p = p,q=q), col="red", type ="p", main = "ST(sgt) & ST(fitdist), nu=p*q, p=2, lambda=0.9", ylab="Density",ylim=c(0,0.8))

lines(xvals, dsstd(xvals, mean = 0, sd = 1, xi = 1.9, nu = p*q), col="blue", type ="l", main = "ST", ylab="Density")


```

