%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% OXFORD THESIS TEMPLATE

% Use this template to produce a standard thesis that meets the Oxford University requirements for DPhil submission
%
% Originally by Keith A. Gillow (gillow@maths.ox.ac.uk), 1997
% Modified by Sam Evans (sam@samuelevansresearch.org), 2007
% Modified by John McManigle (john@oxfordechoes.com), 2015
% Modified by Ulrik Lyngs (ulrik.lyngs@cs.ox.ac.uk), 2018, for use with R Markdown
%
% Ulrik Lyngs, 25 Nov 2018: Following John McManigle, broad permissions are granted to use, modify, and distribute this software
% as specified in the MIT License included in this distribution's LICENSE file.
%
% John tried to comment this file extensively, so read through it to see how to use the various options.  Remember
% that in LaTeX, any line starting with a % is NOT executed.  Several places below, you have a choice of which line to use
% out of multiple options (eg draft vs final, for PDF vs for binding, etc.)  When you pick one, add a % to the beginning of
% the lines you don't want.


%%%%% CHOOSE PAGE LAYOUT
% The most common choices should be below.  You can also do other things, like replacing "a4paper" with "letterpaper", etc.

% This one will format for two-sided binding (ie left and right pages have mirror margins; blank pages inserted where needed):
%\documentclass[a4paper,twoside]{templates/ociamthesis}
% This one will format for one-sided binding (ie left margin > right margin; no extra blank pages):
%\documentclass[a4paper]{ociamthesis}
% This one will format for PDF output (ie equal margins, no extra blank pages):
%\documentclass[a4paper,nobind]{templates/ociamthesis}
%UL 2 Dec 2018: pass this in from YAML
\documentclass[a4paper, nobind]{templates/ociamthesis}

% UL 5 January 2021 - add packages used by kableExtra
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage[colorlinks=false,pdfpagelabels,hidelinks=]{hyperref}
\usepackage{float}


%UL set section header spacing
\usepackage{titlesec}
% 
\titlespacing\subsubsection{0pt}{24pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}

% UL 30 Nov 2018 pandoc puts lists in 'tightlist' command when no space between bullet points in Rmd file
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
 
% UL 1 Dec 2018, fix to include code in shaded environments

%UL set whitespace around verbatim environments
\usepackage{etoolbox}
\makeatletter
\preto{\@verbatim}{\topsep=0pt \partopsep=0pt }
\makeatother

%UL 26 Mar 2019, enable strikethrough
\usepackage[normalem]{ulem}

%UL use soul package for correction highlighting
\usepackage{color, soul}
\usepackage{xcolor}
\definecolor{correctioncolor}{HTML}{CCCCFF}
\sethlcolor{correctioncolor}
\newcommand{\ctext}[3][RGB]{%
  \begingroup
  \definecolor{hlcolor}{#1}{#2}\sethlcolor{hlcolor}%
  \hl{#3}%
  \endgroup
}
\soulregister\ref7
\soulregister\cite7
\soulregister\autocite7
\soulregister\textcite7
\soulregister\pageref7

%%%%%%% PAGE HEADERS AND FOOTERS %%%%%%%%%
\usepackage{fancyhdr}
\setlength{\headheight}{15pt}
\fancyhf{} % clear the header and footers
\pagestyle{fancy}
\renewcommand{\chaptermark}[1]{\markboth{\thechapter. #1}{\thechapter. #1}}
\renewcommand{\sectionmark}[1]{\markright{\thesection. #1}} 
\renewcommand{\headrulewidth}{0pt}

\fancyhead[LO]{\emph{\leftmark}} 
\fancyhead[RE]{\emph{\rightmark}} 

% UL page number position 
\fancyfoot[C]{\emph{\thepage}} %regular pages
\fancypagestyle{plain}{\fancyhf{}\fancyfoot[C]{\emph{\thepage}}} %chapter pages

% JEM fix header on cleared pages for openright
\def\cleardoublepage{\clearpage\if@twoside \ifodd\c@page\else
   \hbox{}
   \fancyfoot[C]{}
   \newpage
   \if@twocolumn\hbox{}\newpage
   \fi
   \fancyhead[LO]{\emph{\leftmark}} 
   \fancyhead[RE]{\emph{\rightmark}} 
   \fi\fi}


%%%%% SELECT YOUR DRAFT OPTIONS
% This adds a "DRAFT" footer to every normal page.  (The first page of each chapter is not a "normal" page.)

% This highlights (in blue) corrections marked with (for words) \mccorrect{blah} or (for whole
% paragraphs) \begin{mccorrection} . . . \end{mccorrection}.  This can be useful for sending a PDF of
% your corrected thesis to your examiners for review.  Turn it off, and the blue disappears.
\correctionstrue

% IP feb 2021: option to include line numbers in PDF

%%%%% BIBLIOGRAPHY SETUP
% Note that your bibliography will require some tweaking depending on your department, preferred format, etc.
% If you've not used LaTeX before, I recommend reading a little about biblatex/biber and getting started with it.
% If you're already a LaTeX pro and are used to natbib or something, modify as necessary.
% Either way, you'll have to choose and configure an appropriate bibliography format...


\usepackage[style=authoryear, sorting=nyt, backend=biber, maxcitenames=2, useprefix, doi=true, isbn=false, uniquename=false]{biblatex}
\newcommand*{\bibtitle}{Works Cited}

\addbibresource{references.bib}


% This makes the bibliography left-aligned (not 'justified') and slightly smaller font.
\renewcommand*{\bibfont}{\raggedright\small}


% Uncomment this if you want equation numbers per section (2.3.12), instead of per chapter (2.18):
%\numberwithin{equation}{subsection}


%%%%% THESIS / TITLE PAGE INFORMATION
% Everybody needs to complete the following:
\title{The importance of higher moments in VaR and CVaR estimation.}
\author{Faes E.\footnote{\href{mailto:Enjo.Faes@student.ams.ac.be}{\nolinkurl{Enjo.Faes@student.ams.ac.be}}}\textsuperscript{}~~~Mertens de Wilmars S.\footnote{\href{mailto:Stephane.MertensdeWilmars@student.ams.ac.be}{\nolinkurl{Stephane.MertensdeWilmars@student.ams.ac.be}}}\textsuperscript{}~~~Pratesi F.\footnote{\href{mailto:Filippo.Pratesi@student.ams.ac.be}{\nolinkurl{Filippo.Pratesi@student.ams.ac.be}}}\textsuperscript{}}
\college{}

% Master's candidates who require the alternate title page (with candidate number and word count)
% must also un-comment and complete the following three lines:

% Uncomment the following line if your degree also includes exams (eg most masters):
%\renewcommand{\submittedtext}{Submitted in partial completion of the}
% Your full degree name.  (But remember that DPhils aren't "in" anything.  They're just DPhils.)
\degree{Master in Finance}
% Term and year of submission, or date if your board requires (eg most masters)
\degreedate{June 2021}


%%%%% YOUR OWN PERSONAL MACROS
% This is a good place to dump your own LaTeX macros as they come up.

% To make text superscripts shortcuts
	\renewcommand{\th}{\textsuperscript{th}} % ex: I won 4\th place
	\newcommand{\nd}{\textsuperscript{nd}}
	\renewcommand{\st}{\textsuperscript{st}}
	\newcommand{\rd}{\textsuperscript{rd}}

%%%%% THE ACTUAL DOCUMENT STARTS HERE
\begin{document}

%%%%% CHOOSE YOUR LINE SPACING HERE
% This is the official option.  Use it for your submission copy and library copy:
\setlength{\textbaselineskip}{22pt plus2pt}
% This is closer spacing (about 1.5-spaced) that you might prefer for your personal copies:
%\setlength{\textbaselineskip}{18pt plus2pt minus1pt}

% You can set the spacing here for the roman-numbered pages (acknowledgements, table of contents, etc.)
\setlength{\frontmatterbaselineskip}{17pt plus1pt minus1pt}

% UL: You can set the line and paragraph spacing here for the separate abstract page to be handed in to Examination schools
\setlength{\abstractseparatelineskip}{13pt plus1pt minus1pt}
\setlength{\abstractseparateparskip}{0pt plus 1pt}

% UL: You can set the general paragraph spacing here - I've set it to 2pt (was 0) so
% it's less claustrophobic
\setlength{\parskip}{2pt plus 1pt}

%
% Oxford University logo on title page
%
\def\crest{{\includegraphics{templates/amslogo.pdf}}}
\renewcommand{\university}{Antwerp Management School}
\renewcommand{\submittedtext}{A thesis submitted for the degree of}
\renewcommand{\submittedtext}{Prof.~dr. Annaert ~Prof.~dr. De Ceuster ~Prof.~dr. Zhang}


% Leave this line alone; it gets things started for the real document.
\setlength{\baselineskip}{\textbaselineskip}


%%%%% CHOOSE YOUR SECTION NUMBERING DEPTH HERE
% You have two choices.  First, how far down are sections numbered?  (Below that, they're named but
% don't get numbers.)  Second, what level of section appears in the table of contents?  These don't have
% to match: you can have numbered sections that don't show up in the ToC, or unnumbered sections that
% do.  Throughout, 0 = chapter; 1 = section; 2 = subsection; 3 = subsubsection, 4 = paragraph...

% The level that gets a number:
\setcounter{secnumdepth}{2}
% The level that shows up in the ToC:
\setcounter{tocdepth}{2}


%%%%% ABSTRACT SEPARATE
% This is used to create the separate, one-page abstract that you are required to hand into the Exam
% Schools.  You can comment it out to generate a PDF for printing or whatnot.

% JEM: Pages are roman numbered from here, though page numbers are invisible until ToC.  This is in
% keeping with most typesetting conventions.
\begin{romanpages}

% Title page is created here
\maketitle

%%%%% DEDICATION -- If you'd like one, un-comment the following.
\begin{dedication}
  For our families and loved ones
\end{dedication}

%%%%% ACKNOWLEDGEMENTS -- Nothing to do here except comment out if you don't want it.
\begin{acknowledgements}
 	First of all, many thanks to our families and loved ones that supported us during the writing of this thesis. Secondly, thank you professors Zhang \footnote{\url{https://www.antwerpmanagementschool.be/nl/faculty/hairui-zhang}}, Annaert\footnote{\url{https://www.antwerpmanagementschool.be/nl/faculty/jan-annaert}} and De Ceuster\footnote{\url{https://www.antwerpmanagementschool.be/nl/faculty/marc-de-ceuster}} for the valuable insights during courses you have given us in preparation of this thesis, the dozens of assignments using the R language and the many questions answered this year. We must be grateful for the classes of R programming by prof Zhang. ~\\

  \noindent Secondly, we must say thanks to \href{https://www.cs.ox.ac.uk/people/ulrik.lyngs/}{Ulrik Lyngs} who made it a bit easier to work together in R with a pre-build template for the university of Oxford, also without which this thesis could not have been written in this format \autocite{lyngsOxforddown2019}. ~\\

  \noindent Finally, we thank \href{https://www.linkedin.com/in/alexios-galanos-64309165/}{Alexios Ghalanos} for making the implementation of GARCH models integrated in R via his package ``rugarch''. By doing this, he facilitated the process of understanding the whole process and doing the analysis for our thesis. ~\\

  \begin{flushright}
  Enjo Faes, \\
  Stephane Mertens de Wilmars, \\
  Filippo Pratesi \\
  Antwerp Management School, Antwerp \\
  27 June 2021
  \end{flushright}
\end{acknowledgements}


%%%%% ABSTRACT -- Nothing to do here except comment out if you don't want it.
\begin{abstract}
	The greatest abstract all times
\end{abstract}

%%%%% MINI TABLES
% This lays the groundwork for per-chapter, mini tables of contents.  Comment the following line
% (and remove \minitoc from the chapter files) if you don't want this.  Un-comment either of the
% next two lines if you want a per-chapter list of figures or tables.

% This aligns the bottom of the text of each page.  It generally makes things look better.
\flushbottom

% This is where the whole-document ToC appears:
\tableofcontents

\listoffigures
	\mtcaddchapter
  	% \mtcaddchapter is needed when adding a non-chapter (but chapter-like) entity to avoid confusing minitoc

% Uncomment to generate a list of tables:
\listoftables
  \mtcaddchapter
%%%%% LIST OF ABBREVIATIONS
% This example includes a list of abbreviations.  Look at text/abbreviations.tex to see how that file is
% formatted.  The template can handle any kind of list though, so this might be a good place for a
% glossary, etc.
\include{front-and-back-matter/abbreviations}

% The Roman pages, like the Roman Empire, must come to its inevitable close.
\end{romanpages}

%%%%% CHAPTERS
% Add or remove any chapters you'd like here, by file name (excluding '.tex'):
\flushbottom

% all your chapters and appendices will appear here
\hypertarget{list-of-symbols}{%
\chapter*{List of Symbols}\label{list-of-symbols}}
\addcontentsline{toc}{chapter}{List of Symbols}

\adjustmtc
\markboth{Introduction}{}

\begin{longtable}[]{@{}ll@{}}
\toprule
\begin{minipage}[b]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
Symbol\strut
\end{minipage} & \begin{minipage}[b]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
Interpretation\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\alpha\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
Significance level, or the percentile chosen for the VaR.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\alpha_0\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The constant in the conditional mean equation. In other papers sometimes referred to as \(\mu\).\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\alpha_1\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The slope in the conditional mean equation.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\beta_0\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The constant in the variance equation and (G)ARCH models. In other papers sometimes referred to as \(\omega\).\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\beta_1\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The parameter estimate of the innovation process in the variance equation and (G)ARCH models. In other papers sometimes referred to as \(\alpha\). This is also known as the ARCH component (\(p\)).\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\beta_2\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The parameter estimate of the autoregressive component in the variance equation and GARCH models. In other papers sometimes referred to as \(\beta\). This is also known as the GARCH componenet (\(q\))\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\gamma\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The leverage term in the asymmetric GARCH models: GJRGARCH and EGARCH.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\varepsilon\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The innovation term or ``noise'' term. The random part or return shock of the previous period in the variance equation in GARCH models.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\zeta\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The time-varying kurtosis parameter in the ACD specification following a piecewise linear dynamic.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\theta\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The vector of parameters to estimate by the log likelihood functions in the maximum likelihood estimation of GARCH and distribution parameters.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\eta\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
This is the tail-thickness parameter of the unconditional and conditional distribution. Following the notation of \textcite{bali2008}, the parameter rises in the SGT distribution. For the T distribution this parameter is equal to the \(\nu/2\).\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\kappa\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The peakedness parameter which is only present in the SGT distribution and equal to 2 for the other distributions used in this paper.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\nu\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The degree of freedom parameter from the T distribution.\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\xi\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The skewness parameter in the skewed distributions (SGT, SGED, ST) and in the GARCH models. Sometimes referred to as \(\lambda\).\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.06}}\raggedright
\(\rho\)\strut
\end{minipage} & \begin{minipage}[t]{(\columnwidth - 1\tabcolsep) * \real{0.94}}\raggedright
The time-varying skewness parameter in the ACD specification following a piecewise linear dynamic.\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{introduction}{%
\chapter*{Introduction}\label{introduction}}
\addcontentsline{toc}{chapter}{Introduction}

\adjustmtc
\markboth{Introduction}{}

\noindent A general assumption in finance is that stock returns are normally distributed. However, various authors have shown that this assumption does not hold in practice: stock returns are not normally distributed \autocites[Among which][]{theodossiou2000,subbotin1923,theodossiou2015}. For example, \textcite{theodossiou2000} mentions that ``empirical distributions of log-returns of several financial assets exhibit strong higher-order moment dependencies which exist mainly in daily and weekly log-returns and prevent monthly, bimonthly and quarterly log-returns from obeying the normality law implied by the central limit theorem. As a consequence, price changes do not follow the geometric Brownian motion.'' So in reality, stock returns exhibit fat-tails and peakedness \autocite{Officer1972}, these are some of the so-called stylized facts of returns. Additionally, a point of interest is the predictability of stock prices \autocite{fama1965,Fama1970,welch2008}. This makes it difficult for corporations to manage market risk, i.e.~the variability of stock prices. ~

Risk, in general, can be defined as the volatility of unexpected outcomes \autocite{jorion2007}. The measure Value at Risk (VaR), developed in response to the financial disaster events of the early 1990s, has been very important in the financial world. Corporations have to manage their risks and thereby include a future risk measurement. The tool of VaR has become a standard measure of risk for many financial institutions going from banks, that use VaR to calculate the adequacy of their capital structure, to other financial services companies to assess the exposure of their positions and portfolios. The 1\% VaR can be defined as the maximum loss of a portfolio, during a time horizon, excluding all the negative events with a combined probability lower than 1\% while the Conditional Value at Risk (CVaR) can be defined as the average of the events that are lower than the VaR. \textcite{bali2008} explains that many implementations of the CVaR have the assumption that asset and portfolio's returns are normally distributed but that this is inconsistent with the evidence. Empiric evidence outlines returns to follow a more skewed distribution with fatter tails than expected under normality. Thus, assuming normality can lead to incorrect numbers, underestimating the probability of extreme events happening and ultimately risks faced by banks.

\noindent This paper has two goals. The first goal is to develop a deeper understanding of GARCH models, their mechanics and the properties of these models in regard to risk management. Second, we aim to replicate and update the research made by \textcite{bali2008} on US indexes, analyzing the dynamics proposed with a European outlook. Namely, we use GARCH models to predict the volatility of the Euro Stoxx 50 return index. After this estimation, we compute VaR and CVaR and conduct a backtest to see if the GARCH models predict the VaR and CVaR appropriately. This is summarized in our research question:

\begin{quote}
\begin{quote}
Do higher moments increase accuracy in the estimation of VaR and CVaR?
\end{quote}
\end{quote}

\noindent The paper is organized as follows. First, chapter \ref{lit-rev} discusses the stylized facts, conditional distributions and the GARCH models. Chapter \ref{dat-and-meth} describes the data used and the methodology followed in modeling the volatility with GARCH models. Then a description is given of the control tests used to evaluate the performances of the different GARCH models and underlying distributions. In chapter \ref{analysis}, the findings are presented and discussed. in chapter \ref{Robustness} the results of some diagnostic tests are shown and interpreted. Finally, chapter \ref{Conclusion} summarizes the results and answers the research question.

\begin{savequote}
Volatility is unobservable. We can only ever estimate and forecast
volatility, and this only within the context of an assumed statistical
model. So there is no absolute `true' volatility: what is `true' depends
only on the assumed model\ldots{}

Moreover, volatility is only a sufficient statistic for the dispersion
of the returns distribution when we make a normality assumption. In
other words, volatility does not provide a full description of the risks
that are taken by the investment unless we assume the investment returns
are normally distributed.
\qauthor{--- Alexander (2008) in \emph{Market Risk Analysis Practical Financial Econometrics}}\end{savequote}



\hypertarget{lit-rev}{%
\chapter{Literature review}\label{lit-rev}}

\minitoc 

\hypertarget{styl-facts}{%
\section{Stylized facts of returns}\label{styl-facts}}

\noindent When analyzing returns as a time-series, we look at log returns. The log returns are similar to simple returns so the stylized facts of returns apply to both. One assumption that is made often in financial applications is that returns are iid, or independently and identically distributed, another is that they are normally distributed. Are these valid assumptions? Below the stylized facts\footnote{Stylized facts are the statistical properties that appear to be present in many empirical asset returns (across time and markets)} following \textcite{annaert2021} for returns are given.

\begin{itemize}
\tightlist
\item
  Returns are \emph{small and volatile} (with the standard deviation being larger than the mean on average).
\item
  Returns have very little serial correlation as mentioned by for example \textcite{bollerslev1987}.
\item
  Returns exhibit conditional heteroskedasticity, or \emph{volatility clustering}. This effect goes back to \textcite{mandelbrot1963}. There is no constant variance (homoskedasticity), but it is time-varying. \textcite{bollerslev1987} describes it as ``rates of return data are characterized by volatile and tranquil periods''. \textcite{alexander2008} says this will have implications for risk models: following a large shock to the market, the volatility changes and the probability of another large shock is increased significantly.
\item
  Returns also exhibit \emph{asymmetric volatility}, in that sense volatility increases more after a negative return shock than after a large positive return shock. This is also called the \emph{leverage effect}. \textcite{alexander2008} mentions that this leverage effect is pronounced in equity markets: usually there is a strong negative correlation between equity returns and the change in volatility.
\item
  Returns are \emph{not normally distributed} which is also one of the conclusions by \textcite{fama1965}. Returns have tails fatter than a normal distribution (leptokurtosis) and thus are riskier than under the normal distribution. Log returns \textbf{can} be assumed to be normally distributed. However, this will be examined in our empirical analysis if this is appropriate. This makes that simple returns follow a log-normal distribution, which is a skewed density distribution. A good summary is given by \textcite{alexander2008} as: ``In general, we need to know more about the distribution of returns than its expected return and its volatility. Volatility tells us the \emph{scale} and the mean tells us the \emph{location}, but the dispersion also depends on the \textbf{\emph{shape}} of the distribution. The best dispersion metric would be based on the entire distribution function of returns.''
\end{itemize}

\noindent Firms holding a portfolio have a lot of things to consider: expected return of a portfolio, the probability to get a return lower than some threshold, the probability that an asset in the portfolio drops in value when the market crashes. All the previous requires information about the return distribution or the density function. What we know from the stylized facts of returns that the normal distribution is not appropriate for returns. In appendix part \ref{conditional-distributions} we summarize some alternative distributions (T, GED, ST, SGED, SGT) that could be a better approximation of returns than the normal one.

\newpage

\hypertarget{vol-mod}{%
\section{Volatility modeling}\label{vol-mod}}

\hypertarget{rolling-volatility}{%
\subsection{Rolling volatility}\label{rolling-volatility}}

\noindent When volatility needs to be estimated on a specific trading day, the method used as a descriptive tool would be to use rolling standard deviations. \textcite{engle2001} explains the calculation of rolling standard deviations, as the standard deviation over a fixed number of the most recent observations\footnote{For example, for the past month it would then be calculated as the equally weighted average of the squared deviations from the mean (i.e.~residuals) from the last 22 observations (the average amount of trading or business days in a month). All these deviations are thus given an equal weight. Also, only a fixed number of past recent observations is examined.}. Engle regards this formulation as the first ARCH model.

\hypertarget{univ-garch}{%
\subsection{From ARCH to GARCH models}\label{univ-garch}}

\noindent Autoregressive Conditional Heteroscedasticity (ARCH) models, proposed by \textcite{engle1982}, was in the first case not used in financial markets but on inflation. Since then, it has been used as one of the workhorses of volatility modeling.

There are three building blocks of the ARCH model: returns, the innovation process and the variance process (or volatility function), written out for an ARCH(1) in respectively equation \eqref{eq:eq1}, \eqref{eq:eq2} and \eqref{eq:eq3}. Returns are written as a constant part (\(\alpha_0\)) and an unexpected part, called noise or the innovation process. The innovation process is the volatility (\(\sigma_t\)) times \(z_t\), which is an independent identically distributed random variable with a mean of 0 (zero-mean) and a variance of 1 (unit-variance). The independent (\textbf{i}id), notes the fact that the \(z\)-values are not correlated, but completely independent of each other. The distribution is not yet assumed. The third component is the variance process or the expression for the volatility. The variance is given by a constant \(\omega\), plus the random part which depends on the return shock of the previous period squared (\(\varepsilon_{t-1}^2\)). In that sense when the uncertainty or surprise in the last period increases, then the variance becomes larger in the next period. The element \(\sigma_t^2\) is thus known at time \(t-1\), while it is a deterministic function of a random variable observed at time \(t-1\) (i.e.~\(\varepsilon_{t-1}^2\)).

\begin{equation} 
y_{t} = \alpha_0 + \alpha_1 \times \varepsilon_t
 \label{eq:eq1} 
\end{equation}
\vspace{-15mm}

\begin{equation}
\varepsilon_{t} = \sigma_t \times z_t, \ where \ z_t \stackrel{iid}{\sim} (0,1)
 \label{eq:eq2} 
\end{equation}
\vspace{-15mm}

\begin{equation}
\sigma_{t}^{2} = \beta_0 + \beta_1 \times  \varepsilon_{t-1}^2 
 \label{eq:eq3}
\end{equation}

The full description of the ARCH model is given in appendix part \ref{ARCH}.

\noindent An improvement of the ARCH model is the Generalized Autoregressive Conditional Heteroscedasticity (GARCH)\footnote{\emph{Generalized} as it is a generalization by \textcite{bollerslev1986} of the ARCH model of \textcite{engle1982}. \emph{Autoregressive,} as it is a time series model with an autoregressive form (regression on itself). \emph{Conditional heteroscedasticity,} while time variation in conditional variance is built into the model \autocite{alexander2008}.}. This model and its variants come in to play because of the fact that calculating standard deviations through rolling periods, gives an equal weight to distant and nearby periods, by such not taking into account empirical evidence of volatility clustering, which can be identified as positive autocorrelation in the absolute returns. GARCH models are an extension to ARCH models, as they incorporate both a novel moving average term (not included in ARCH) and the autoregressive component. Furthermore, a second extension is changing the assumption of the underlying distribution. As already explained, the normal distribution is an unrealistic assumption, so other distributions which are described in part \ref{conditional-distributions} will be used. As \textcite{alexander2008} explains, this does not change the formulae of computing the volatility forecasts but it changes the functional form of the likelihood function\footnote{which makes the maximum likelihood estimation explained in part \ref{garch-method} complex with more parameters that have to be estimated.}. An overview (of a selection) of investigated GARCH models is given in the following table.

\newpage

\begin{longtable}[]{@{}ll@{}}
\caption{GARCH models, the founders}\tabularnewline
\toprule
Author(s)/user(s) & Model\tabularnewline
\midrule
\endfirsthead
\toprule
Author(s)/user(s) & Model\tabularnewline
\midrule
\endhead
\textcite{engle1982} & ARCH model\tabularnewline
\textcite{bollerslev1986} & GARCH model\tabularnewline
\textcite{bollerslev1986} & IGARCH model\tabularnewline
\textcite{nelson1991} & EGARCH model\tabularnewline
\textcite{glosten1993} & GJRGARCH model\tabularnewline
\textcite{engle1993} & NAGARCH model\tabularnewline
\textcite{zakoian1994} & TGARCH model\tabularnewline
\textcite{taylor1986} and \textcite{schwert1989} & AVGARCH model\tabularnewline
\textcite{morganguarantytrustcompany1996} & EWMA or RiskMetrics model\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{acd-models}{%
\section{ACD models}\label{acd-models}}

An extension to GARCH models was proposed by \textcite{hansen1994}, the autoregressive conditional density estimation model (referred to as ACD models, sometimes ARCD). It focuses on time variation in higher moments (skewness and kurtosis), because the degree and frequency of extreme events seem to be not expected by traditional models. Some GARCH models are already able to capture the dynamics by relying on a different unconditional distribution than the normal distribution (for example skewed distributions like the SGED, SGT), or a model that allows to model these higher moments. However, \textcite{ghalanos2016} mentions that these models also assume the shape and skewness parameters to be constant (not time varying). As Ghalanos mentions: ``the research on time varying higher moments has mostly explored different parameterizations in terms of dynamics and distributions with little attention to the performance of the models out-of-sample and ability to outperform a GARCH model with respect to VaR.'' Also one could question the marginal benefits of the ACD, while the estimation procedure is not simple (nonlinear bounding specification of higher moment distribution parameters and interaction). So, are skewness (skewness parameter) and kurtosis ( shape parameters) time varying? The literature investigating higher moments has arguments for and against this statement. In part \ref{acd-models-meth} the specification is given.

\hypertarget{value-at-risk}{%
\section{Value at Risk}\label{value-at-risk}}

Value-at-Risk (VaR) is a risk metric developed simultaniously by \textcite{markowitz1952} and Roy1952 to calculate how much money an investment, portfolio, department or institution such as a bank could lose in a market downturn, though in this period it remained mostly a theoretical discussion due to lacking processing power and industry demand for risk management measures. Another important document in literature is the \emph{1996 RiskMetrics Technical Document}, composed by RiskMetrics\footnote{RiskMetrics Group was the market leader in market and credit risk data and modeling for banks, corporate asset managers and financial intermediaries \autocite{alexander2008}.}, \textcite{morganguarantytrustcompany1996} (part of JP Morgan), gives a good overview of the computation, but also made use of the name ``value-at-risk'' over equivalents like ``dollars-at-risk'' (DaR), ``capital-at-risk'' (CaR), ``income-at-risk'' (IaR) and ``earnings-at-risk'' (EaR). According to \textcite{holton2002} VaR gained traction in the last decade of the 20\textsuperscript{th} century when financial institutions started using it to determine their regulatory capital requirements. A \(VaR_{99}\) finds the amount that would be the greatest possible loss in 99\% of cases. It can be defined as the threshold value \(\alpha\). Put differently, in 1\% of cases the loss would be greater than this amount.It is specified as in \eqref{eq:eq22}. Christofferson2001 puts forth a general framework for specifying VaR models and comparing between two alternatives models.

\begin{align}
Pr(y_t \le \alpha | \Omega_{t-1}) \equiv \phi
 \label{eq:eq22}
\end{align}

With \(y_t\) expected returns in period t, \(\Omega_{t-1}\) the information set available in the previous period and \(\phi\) the chosen confidence level.

\hypertarget{conditional-value-at-risk}{%
\section{Conditional Value at Risk}\label{conditional-value-at-risk}}

One major shortcoming of the VaR is that it does not provide information on the probability distribution of losses beyond the threshold amount. As VaR lacks subadditivity of different percentile outcomes, {[}Artzner1998{]} reject it as a coherent measure of risk. This is problematic, as losses beyond this amount would be more problematic if there is a large probability distribution of extreme losses, than if losses follow say a normal distribution. To solve this issue, they provide a conceptual idea of a Conditional VaR (CVaR) which quantifies the average loss one would expect if the threshold is breached, thereby taking the distribution of the tail into account. Mathematically, a \(cVaR_{99}\) is the average of all the \(VaR\) with a confidence level equal to or higher than 99. It is commonly referred to as expected shortfall (ES) sometimes and was written out in the form it is used by today by \autocite{bertsimas2004}. It is specified as in \eqref{eq:eq23}.

To calculate \(\alpha\), VaR and CVaR require information on the expected distribution mean, variance and other parameters, to be calculated using the previously discussed GARCH models and distributions.

\begin{align}
Pr(y_t \le \alpha | \Omega_{t-1}) \equiv \int_{-\infty}^{\alpha} \! f(y_t | \Omega_{t-1}) \, \mathrm{d}y_t = \phi
 \label{eq:eq23}
\end{align}

With the same notations as before, and \(f\) the (conditional) probability density function of \(y_t\).

According to the BIS framework, banks need to calculate both \(VaR_{99}\) and \(VaR_{97.5}\) daily to determine capital requirements for equity, using a minimum of one year of daily observations \autocite{baselcommitteeonbankingsupervision2016}. Whenever a daily loss is recorded, this has to be registered as an exception. Banks can use an internal model to calculate their VaRs, but if they have more than 12 exceptions for their \(VaR_{99}\) or 30 exceptions for their \(VaR_{97.5}\) they have to follow a standardized approach.Similarly, banks must calculate \(CVaR_{97.5}\).

\hypertarget{past-lit}{%
\section{Past literature on the consequences of higher moments for VaR determination}\label{past-lit}}

Here comes the discussion about studies that have looked at higher moments and VaR determination. Also a summary of studies that discusses time-varying higher moments, but not a big part, while it is also only a small part of the empirical findings (couple of GARCH-ACD models).

\begin{longtable}[]{@{}ll@{}}
\caption{Higher moments and VaR}\tabularnewline
\toprule
Author & Higher moments\tabularnewline
\midrule
\endfirsthead
\toprule
Author & Higher moments\tabularnewline
\midrule
\endhead
\textcite{hansen1994} & Skewness and kurtosis extended ARCH-model\tabularnewline
\textcite{harvey1999} & Skewness, Effect of higher moments on lower moments\tabularnewline
\textcite{brooks2005} & Kurtosis, Time varying degrees of freedom\tabularnewline
\bottomrule
\end{longtable}

\noindent While it is relatively straightforward to include unconditional higher-moments in VaR and CVaR calculations, it is less simple to do so when the higher moments (in addition to the variance) are time-varying. \textcite{hansen1994} extends the ARCH model to include time-varying moments beyond mean and variance. While mean returns and variance are usually the parameters of most interest, disregarding these higher moments could provide an incomplete description of a conditional distribution. The model proposed by \textcite{hansen1994} allows for skewness and shape parameters to vary in a skewed-t density function through specifying them as functions of their errors in previous periods (in an similar way how variance is estimated). Applications on U.S. Treasuries and exchange rates are discussed.~\textbackslash{}

\noindent \textcite{harvey1999} extends a GARCH(1,1) model to include time varying skewness by estimating it jointly with time varying variance using a skewed t distribution. They find a significant impact of skewness on conditional volatility, suggesting that these moments should be jointly estimated for efficiency. Changes in conditional skewness have an impact on the persistence of volatility shocks. They also find that including skewness causes the leverage effects of variance to dissapear. They apply their methods on different stock indices (both developed and emerging) at daily, weekly and monthly frequency.~\textbackslash{}

\noindent \textcite{brooks2005} proposes a model based on a t-distribution that allows for both the variance and the degrees of freedom to be time-varying, independently from eachother. Their model allows for both assymetric variance and kurtosis through an indicator function (which has a positive effect on these moments only when the shock is in the right tail). They apply their model on different financial assets in the U.S. and U.K. at daily frequency.

\hypertarget{dat-and-meth}{%
\chapter{Data and methodology}\label{dat-and-meth}}

\chaptermark{Data and methodology}

\minitoc 

\hypertarget{data}{%
\section{Data}\label{data}}

\noindent We worked with daily returns on the Euro Stoxx 50 Return Index\footnote{The same analysis has been performed for the INDEX 1, INDEX 2, INDEX 3 and the INDEX 4 indexes with the same conclusions. The findings of these researches are available upon requests.} retrieved from Datastream denoted in EUR from 02 January, 2001 to 19 May, 2021. The choice of daily data is motivated as follows. The primary interest in this paper is (c)VaR models for banks internal trading desks. Their positions are usually short-term, making risk management at the daily level the most appropriate. As such, in reference to the literature review, regulators require VaR forecast for one day in advance. All following analysis could be applied on monthly returns as well. To get some intuition on how returns differ at a wider aggregation, table X in the appendix shows summary statistics for monthly data instead of daily. The Euro Stoxx 50 is the leading blue-chip index of the Eurozone, was founded in 1999 and covers 50 of the most liquid and largest (in terms of free-float market capitalization) stocks. For its composition and computation we refer to the factsheet \autocite{EUROSTOXXFactSheet}. Given that in the 20th century computing return series was time consuming, the Eurostoxx 50 Return index is x shorter than the Euro Stoxx 50 Price index (going back to 2001). As a robustness check, we ran all subsequent analysis for the longer price index as well. This did not yield a qualitative difference in terms of most efficient model(s). ~\\

\noindent Table \ref{tab:dsTable} provides the main statistics describing the return series analyzed. Let daily returns be computed as \(R_{t}=100\left(\ln P_{t}-\ln P_{t-1}\right)\),where \(P_{t}\) is the index price at time \(t\) and \(P_{t-1}\) is the index price at \(t-1\).~\\

\noindent The arithmetic mean of the series is 0.01\% with a standard deviation of 1.44\% and a median of 0.02 which translate to an annualized mean of 2.57\% and an annualized standard deviation of 22.85\%. The skewness statistic is highly significant and negative at -0.22 and the excess kurtosis is also highly significant and positive at 6.54. These 2 statistics give an overview of the distribution of the returns which has thicker tails than the normal distribution with a higher presence of left tail observations. A formal test such as the Jarque-Bera one with its statistic at 739.89 and a high statistical significance, confirms the non normality feeling given by the Skewness and Kurtosis.~\\

\begin{table}[h!]

\caption{\label{tab:dsTable}Summary statistics of the returns}
\centering
\begin{threeparttable}
\begin{tabular}[t]{lll}
\toprule
Statistics & Euro Stoxx 50 & Standardized Residuals\\
\midrule
Arithmetic Mean & 0.0102 & -0.0512\\
Median & 0.0152 & -0.0314\\
Maximum & 10.4372 & 5.8561\\
Minimum & -13.2164 & -6.4432\\
Stdev & 1.4391 & 0.9986\\
\addlinespace
Skewness & -0.2191 & -0.3285\\
 & (0***) & (0***)\\
Excess Kurtosis & 6.5382 & 1.7055\\
 & (0***) & (0***)\\
Jarque-Bera & 9511.1796*** & 739.8884***\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item Notes
\item[1] This table shows the descriptive statistics of the daily percentage returns of Euro Stoxx 50 over the period 2001-01-03 to 2021-05-19 (5316 observations). Including arithmetic mean, median, maximum, minimum, standard deviation. The skewness, excess kurtosis with p-value and signicance and the Jarque-Bera test with significance.
\item[2] The standardized residual is derived from a maximum likelihood estimation (simple GARCH model) as follows:  $ R_t=\alpha_0+\alpha_1 R_{t-1}+z_t \sigma_t \\ \sigma_t^2=\beta_0+\beta_1 \sigma_{t-1}^2 z_{t-1}^2+\beta_2 \sigma_{t-1}^2, \\$ Where $z$ is the standard residual (assumed to have a normal distribution).
\item[3] *, **, *** represent significance levels at the 5%, 1% and <1%.
\end{tablenotes}
\end{threeparttable}
\end{table}

\noindent The right column of table \ref{tab:dsTable} displays the same descriptive statistics but for the standardizes residuals obtained from a simple GARCH model as mentioned in table \ref{tab:dsTable} in Note 2. Again, Skewness statistic at -0.328 with a high statistical significance level and the excess Kurtosis at 1.706 also with a high statistical significance, suggest a non normal distribution of the standardized residuals and the Jarque-Bera statistic at 9511.18, given its high significance, confirms the rejection of the normality assumption.~\\

\noindent As can be seen in figure \ref{fig:plot1} the Euro area equity and later, since 1999 the Euro Stoxx 50, went up during the tech (``dot com'') bubble reaching an ATH of €1734.84. Then, there was a correction to boom again until the burst of the 2008 financial crisis. After which it decreased significantly. With an ATL at 12 March, 2003 of €405.23. There is an improvement, but then the European debt crisis, with its peak in 2010-2012, occurred. From then there was some improvement until the ``health crisis'', which arrived in Europe, February 2020. This crisis recovered very quickly reaching already values higher then the pre-COVID crisis level.

\begin{figure}[h]

{\centering \includegraphics[width=0.95\linewidth]{_main_files/figure-latex/plot1-1} 

}

\caption{Euro Stoxx 50 prices}\label{fig:plot1}
\end{figure}

\noindent In figure \ref{fig:plot2} the daily log-returns are visualized. A stylized fact that is observable is the volatility clustering. As can be seen: periods of large volatility are mostly followed by large volatility and small volatility by small volatility.

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth]{figures/vol-clustering-finalized-RI} 

}

\caption{Euro Stoxx 50 log returns}\label{fig:plot2}
\end{figure}

\clearpage
\newpage

\noindent In figure \ref{fig:plot4} the density distribution of the log returns are examined. As can be seen, as already mentioned in part \ref{styl-facts}, log returns are not really normally distributed.

\begin{figure}[h]

{\centering \includegraphics[width=0.75\linewidth]{_main_files/figure-latex/plot4-1} 

}

\caption{Density vs. Normal Euro Stoxx 50 log returns}\label{fig:plot4}
\end{figure}

\noindent In figure \ref{fig:acfplots} the prediction errors (in absolute values and squared) are visualized in autocorrelation function plots. It is common practice to check this, while in GARCH models the variance is for a large extent driven by the square of the prediction errors. The first component\footnote{\(\alpha_0\) is most of the time referred to as the \(\mu\) in the conditional mean equation. Here we have followed \textcite{bali2008}.} \(\alpha_0\) is set equal to the sample average. As can be seen there is presence of large positive autocorrelation. This reflects, again, the presence of volatility clusters.

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth]{_main_files/figure-latex/acfplots-1} 

}

\caption{Absolute prediction errors}\label{fig:acfplots}
\end{figure}

\clearpage

\hypertarget{methodology}{%
\section{Methodology}\label{methodology}}

\hypertarget{garch-method}{%
\subsection{Garch models}\label{garch-method}}

\noindent As already mentioned in part \ref{univ-garch}, the following models: SGARCH, EGARCH, IGARCH, GJRGARCH, NGARCH, TGARCH and NAGARCH (or TSGARCH) will be estimated. Additionally the distributions will be examined as well, including the normal, student-t distribution, skewed student-t distribution, generalized error distribution, skewed generalized error distribution and the skewed generalized t distribution. They will be estimated using maximum likelihood\footnote{As already mentioned, fortunately, \textcite{alexios2020} has made it easy for us to implement this methodology in the R language{[}\^{}data-meth-4{]} \autocite{Rteam} with the package ``rugarch'' v.1.4-4 (\emph{R univariate garch}), which gives us a bit more time to focus on the results and the interpretation.}.~\\

\noindent Maximum likelihood estimation is a method to find the distribution parameters that best fit the observed data, through maximization of the likelihood function, or the computationally more efficient log-likelihood function (by taking the natural logarithm). It is assumed that the return data is i.i.d. and that there is some underlying parametrized density function \(f\) with one or more parameters that generate the data, defined as a vector \(\theta\) in equation \eqref{eq:pdf}. These functions are based on the joint probability distribution of the observed data as in equation \eqref{eq:logl}. Subsequently, the (log)likelihood function is maximized using an optimization algorithm shown inequation \eqref{eq:optim}.

\begin{align} 
  y_1,y_2,...,y_N \sim i.i.d
    \\
  y_i \sim f(y|\theta)
 \label{eq:pdf}
\end{align}

\begin{align} 
 L(\theta) = \prod^N_{i=1}f(y_i|\theta)
 \label{eq:logl}
\end{align}

\[\log(L(\theta)) = \sum^N_{i=1} \log f(y_i |\theta)\]

\begin{equation} 
\theta^{*} = arg \max_{\theta} [ L] 
 \label{eq:optim}
\end{equation}

\begin{equation} 
\theta^{*} = arg \max_{\theta} [\log(L)]
\end{equation}

\noindent After estimation of the GARCH models in-sample, out-sample analysis is done by performing a rolling window approach. With assumptions: a window of 2500 observations and re-estimation every year.

\hypertarget{acd-models-meth}{%
\subsection{ACD models}\label{acd-models-meth}}

\noindent Following \textcite{ghalanos2016}, arguments of ACD models are specified as in \textcite{hansen1994}. The skewness and kurtosis (shape) parameters which are constant in GARCH models (or time-invariant), are here time-varying following a piecewise linear dynamic. In equation \eqref{eq:acd} the parameters of the GARCH-ACD model are specified.

\begin{equation}
\begin{array}{l}
y_{t}=\alpha_0 + \alpha_1 \times \varepsilon_{t}, \\
\varepsilon_{t}= \sigma_{t} \times z_{t}, \\
z_{t} \sim \Delta\left(0,1, \rho_{t}, \zeta_{t}\right), \\
\sigma_{t}^{2}=\beta_0+\beta_{1} \varepsilon_{t-1}^{2}+\beta_{2} \sigma_{t-1}^{2}, \\
\rho_{t}= \chi_{0}+\chi_{1} z_{t-1} I_{z_{t-1}<x}+\chi_{2} z_{t-1} I_{z_{t-1} \geqslant x}+\xi_{1} \bar{\rho}_{t-1},\\
\zeta_{t}=\kappa_{0}+\kappa_{1}\left|z_{t-1}\right| I_{z_{t-1}<x}+\kappa_{2}\left|z_{t-1}\right| I_{z_{t-1} \geqslant x}+\psi_{1} \bar{\zeta}_{t-1},
\end{array}
\label{eq:acd}
\end{equation}

\noindent where \(y_t\), \(z_t\) and \(\sigma_t\) are familiar from GARCH models. \(\rho_t\) and \(\zeta_t\) are respectively the time-varying skewness and shape parameter (with shape parameter meaning here the tail-tickness) and the standardized residuals \(z_t\) follows a distribution \(\Delta\) that has a skewness and shape parameter. \(\rho_t\) and \(zeta_t\) are following a piecewise linear dynamic with \(I\) the indicator variable (taking one if the underlying expression is true, 0 otherwise). \(x\) is a treshold value set to 0.

\noindent Again \textcite{ghalanos2016} makes it easier to implement the somewhat complex ACD models using the R language with package ``racd''.

\hypertarget{analysis-tests-var-and-cvar}{%
\subsection{Analysis Tests VaR and CVaR}\label{analysis-tests-var-and-cvar}}

\hypertarget{unconditional-coverage-test-of-kupiec1995}{%
\subsubsection{\texorpdfstring{Unconditional coverage test of \textcite{kupiec1995}}{Unconditional coverage test of @kupiec1995}}\label{unconditional-coverage-test-of-kupiec1995}}

\noindent A number of tests are computed to see if the value-at-risk estimations capture the actual losses well. A first one is the unconditional coverage test by \textcite{kupiec1995}. The unconditional coverage or proportion of failures method tests if the actual value-at-risk exceedances are consistent with the expected exceedances (a chosen percentile, e.g.~1\% percentile) of the VaR model. Following \textcite{kupiec1995} and \textcite{ghalanos2020}, the number of exceedences follow a binomial distribution (with thus probability equal to the significance level or expected proportion) under the null hypothesis of a correct VaR model. The test is conducted as a likelihood ratio test with statistic like in equation \eqref{eq:uccov}, with \(p\) the probability of an exceedence for a confidence level, \(N\) the sample size and \(X\) the number of exceedences. The null hypothesis states that the test statistic \(L R^{u c}\) is \(\chi^2\)-distributed with one degree of freedom or that the probability of failure \(\hat p\) is equal to the chosen percentile \(\alpha\).

\begin{align}
L R^{u c}=-2 \ln \left(\frac{(1-p)^{N-X} p^{X}}{\left(1-\frac{X}{N}\right)^{N-X}\left(\frac{X}{N}\right)^{X}}\right)
\label{eq:uccov}
\end{align}

\hypertarget{conditional-coverage-test-of-christoffersen2001}{%
\subsubsection{\texorpdfstring{Conditional coverage test of \textcite{christoffersen2001}}{Conditional coverage test of @christoffersen2001}}\label{conditional-coverage-test-of-christoffersen2001}}

\noindent \textcite{christoffersen2001} proposed the conditional coverage test. It is tests for unconditional coverage and serial independence. The serial independence is important while the \(L R^{u c}\) can give a false picture while at any point in time it classifies inaccurate VaR estimates as ``acceptably accurate'' \autocite{bali2007}. For a certain VaR estimate an indicator variable, \(I_t(\alpha)\), is computed as equation \eqref{eq:ccov}.

\begin{align}
I_{t}(\alpha)=\left\{\begin{array}{ll}
1 & \text { if exceedence occurs } \\
0 & \text { if no exceedence occurs }
\end{array} .\right.
\label{eq:ccov}
\end{align}

\noindent It involves a likelihood ratio test's null hypothesis is that the statistic is \(\chi^2\)-distributed with two degrees of freedom or that the probability of violation \(\hat p\) (unconditional coverage) as well as the conditional coverage (independence) is equal to the chosen percentile \(\alpha\). While it tests both unconditional coverage as independence of violations, only this test has been performed and the unconditional coverage test is not reported.

\hypertarget{dynamic-quantile-test}{%
\subsubsection{Dynamic quantile test}\label{dynamic-quantile-test}}

\noindent \textcite{engle2004} provides an alternative test to specify if a VaR model is appropriately specified by proposing the dynamic quantile test. This test specifies the occurence of an exceedance (here hit) as in \eqref{eq:dq1}, with \(I(.)\) a function that indicates when there is a hit, based on the actual return being lower than the predicted VaR. \(\theta\) is the confidence level. They test jointly \(H_0\) that the expected value of hit is zero and that it is uncorrelated with any variables known at the beginning of the period (\(B\)), notably the current VaR estimate and hits in previous periods, specified as lagged hits. This is done by regressing hit on these variables as in \eqref{eq:dq2}. \(X\delta\) corresponds to the matrix notation. Under \(H_0\), this regression should have no explanatory power. As a final step, a \(\chi^2\)-distributed test statistic with \(m\) degrees of freedom equal to the parameters to be estimated (constant, number of hits and VaR estimate) is constructed as in \eqref{eq:dq3}.

\begin{align}
Hit_{t}=I\left(R_{t}<-\operatorname{VaR}_{t}(\theta)\right)-\theta,
\label{eq:dq1}
\end{align}

\begin{align}
\begin{array}{c}
Hit_{t}=\delta_{0}+\delta_{1} H i t_{t-1}+\ldots+\delta_{p} Hit_{t-p}+\delta_{p+1} VaR_{t}+ \\
\delta_{p+2} I_{year1, t}+\ldots+\delta_{p+2+n} I_{year n, t}+u_{t} \end{array}
\label{eq:dq2}
\end{align}

\[Hit_{t}=X \delta+u_{t} \quad u_{t}=\left\{\begin{array}{ll}
-\theta & \text { prob }(1-\theta) \\
(1-\theta) & \text { prob } \theta
\end{array}\right.\]

\begin{align}
\frac{\hat{\delta}_{O L S}^{\prime} X^{\prime} X \hat{\delta}_{O L S}^{a}}{\theta(1-\theta)} \sim \chi^{2}(m)
\label{eq:dq3}
\end{align}

\hypertarget{cvar-test}{%
\subsubsection{CVaR Test}\label{cvar-test}}

The Expected Shortfall (or CVaR) test by \textcite{mcneil2000} tests whether the excess conditional shortfall has a mean of zero. Under the alternative hypothesis, this mean is greater than zero. This test uses a one sided t-statistic and bootstrapped p-values, as the distribution of the excess conditional shortfall is not assumed to be normal.

\hypertarget{analysis}{%
\chapter{Empirical Findings}\label{analysis}}

\minitoc 

\hypertarget{density-of-the-returns}{%
\section{Density of the returns}\label{density-of-the-returns}}

\hypertarget{mle-distribution-parameters}{%
\subsection{MLE distribution parameters}\label{mle-distribution-parameters}}

In table \ref{tab:MLEtable} we can see the estimated parameters of the unconditional distribution functions. Note that the student-t and skewed student-t distribution are usually noted with degrees of freedom as parameters. For consistency, we have parameterized them using limiting cases of the SGT-distribution. Note that to read the degrees of freedom for the two distributions, it is simply \(2\eta\). They are presented for the Skewed Generalized T-distribution (SGT) and limiting cases thereof previously discussed. Additionally, maximum likelihood score and the Akaike Information Criterion (AIC) is reported to compare goodness of fit of the different distributions but also taking into account simplicity of the models. We find that the SGT-distribution has the highest maximum likelihood score of all. All other distributions have relatively similar likelihood scores, though slightly lower and are therefore not the optimal distributions. However, when considering AIC it is a tie between SGT and SGED. This provides some indication that we have a valid case to test the suitability of different SGED-GARCH VaR models as an alternative for the SGT-GARCH VaR models. While sacrificing some goodness of fit, the SGED distribution has the advantage of requiring one parameter less, which could possibly result in less errors due to misspecification and easier implementation. For the SGT parameters the standard deviation and skewness are both significant at the 1\% level. For the SGED parameters, the standard deviation and the skewness are both significant at respectively the 1\% and 5\% level. Both distributions are right-skewed. For both distributions the shape parameters are significant at the 1\% level, though the \(q\) parameter was not estimated as it is by design set to infinity due to the SGED being a limiting case of SGT.\footnote{To check whether the relative ranking of distributions still holds in different periods, we have calculated the maximum likelihood score and AIC for three smaller periods: The period up to the dotcom collapse (1987-2001), up to the GFC (2002-2009) and up to the present Covid-crash (2009-2021). There is no qualitative difference in relative ranking with these subsamples. Results are reported in the appendix.} ~\\

\noindent Additionally, for every distribution fitted with MLE, plots are generated to compare the theoretical distribution with the observed returns. We see that except for the normal distribution which is quite off, the theoretical distributions are close to the actual data, except that they are too peaked. This problem is the least present for the SGT distribution.

\begin{landscape}\begin{table}[h!]

\caption{\label{tab:MLEtable}Maximum likelihood estimates of unconditional distribution functions}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{llllllrr}
\toprule
$dist$ & $\alpha$ & $\beta$ & $\xi$ & $\kappa$ & $\eta$ & $LLH$ & AIC\\
\midrule
SGT & 0.014 & 1.441 & -0.02 & 1.233 & 4.959 & -8850.419 & 17710.84\\
 & (0.025) & (0.031)*** & (0.016) & (0.085)*** & (1.368)*** &  & \\
SGED & 0.015 & 1.42 & 0.008 & 0.898 & Inf & -8859.217 & 17710.84\\
 & (0.003)*** & (0.015)*** & (0.002)*** & (0.018)*** &  &  & \\
GED & 0 & 1.418 & 0 & 0.899 & Inf & -8859.537 & 17725.07\\
\addlinespace
 & (0.002) & (0.023)*** &  & (0.022)*** &  &  & \\
ST & 0.012 & 1.635 & -0.043 & 2 & 2.817 & -8873.843 & 17755.69\\
 & (0.02) & (0.076)*** & (0.016)*** &  & (0.132)*** &  & \\
T & 0.045 & 1.64 & 0 & 2 & 1.403 & -8877.165 & 17760.33\\
 & (0.015)*** & (0.078)*** &  &  & (0.133)*** &  & \\
\addlinespace
Normal & 0.01 & 1.439 & 0 & 2 & Inf & -9477.660 & 18959.32\\
 & (0.02) & (0.014)*** &  &  &  &  & \\
\bottomrule
\end{tabular}}
\begin{tablenotes}
\item \textit{Notes:} 
\item Table contains parameter estimates for SGT-distribution and some of its limiting cases. The underlying data is the daily return series of the Euro Stoxx 50 for the period between December 31. 1986 and April 27. 2021. Standard errors are reported between brackets. $LLH$ is the maximum log-likelihood value. *, ** and *** point out significance at 10, 5 and 1 percent level.
\end{tablenotes}
\end{threeparttable}
\end{table}
\end{landscape}

\newpage

\hypertarget{constant-higher-moments}{%
\section{Constant higher moments}\label{constant-higher-moments}}

\noindent Table \ref{tab:Table3} presents the maximum likelihood estimates for 8 GARCH models based on the ST distribution with constant skewness and kurtosis parameters (robust white errors are presented in parenthesis). The parameter \(\alpha_0\) are only statistically significant for the SGARCH, IGARCH and EWMA model with a value close to 0. The AR(1) coefficient, \(\alpha_1\), has parameters going from -0.049 to -0.032 with \(p\) values ranging from 0.011 to 0.014 suggesting significance, but indicating very small negative autocorrelation. The GARCH parameters in the conditional variance equations (\(\beta_0\)) are generally statistically significant except for the EGARCH model. The results of \(\beta_1\) and \(\beta_2\) show the presence of significant time-variation in the conditional volatility of the Euro Stoxx 50, in fact, the sum of \(\beta_1\) and \(\beta_2\) for the GARCH parameters is close to one (from 0.827 to 1), suggesting the presence of persistence in the volatility of the returns. The parameter \(\xi\) is highly significant for all the 8 models tested with values ranging from 0.885 to 0.918 confirming the presence of skewness in the returns. The shape parameter \(\eta\), which, in our case, measures the number of degrees of freedom divided by two, determining the tail behavior, is significant for all the models and ranges between 3.153 and 4.0635. The parameter \(\gamma\), which is present only for EGARCH and GJRGARCH is significant and with values around 0.14. The absolute value function in family GARCH models (NAGARCH, TGARCH and AVGARCH) is subject to the \(shift\) and the \(rot\) parameters whose values are always positive and statistically significant. According to the log likelihood values (\(LLH\)), displayed in table \ref{tab:Table3}, the model with the highest value is AVGARCH while, excluding the non-standard GARCH models from the analysis, the model that performs best is EGARCH.~\\

\noindent Table \ref{tab:Table3b} shows a very similar picture for the GARCH-SGED models as the GARCH-ST models.

\begin{landscape}\begin{table}

\caption{\label{tab:Table3}Maximum likelihood estimates of the ST-GARCH models with constant skewness and kurtosis parameters}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllllll}
\toprule
 & SGARCH & IGARCH & EGARCH & GJRGARCH & EWMA & NAGARCH & TGARCH & AVGARCH\\
\midrule
$\alpha_0$ & 0.052 & 0.052 & 0.014 & 0.019 & 0.055 & 0.004 & 0.013 & 0.003\\
 & (0.012)*** & (0.013)*** & (0.011) & (0.012) & (0.014)*** & (0.012) & (0.013) & (0.013)\\
$\alpha_1$ & -0.048 & -0.048 & -0.033 & -0.043 & -0.049 & -0.034 & -0.038 & -0.032\\
 & (0.013)*** & (0.013)*** & (0.012)*** & (0.012)*** & (0.014)*** & (0.012)*** & (0.011)*** & (0.012)**\\
$\beta_0$ & 0.017 & 0.014 & 0.004 & 0.021 & 0 & 0.024 & 0.023 & 0.024\\
\addlinespace
 & (0.004)*** & (0.004)*** & (0.003) & (0.004)*** &  & (0.003)*** & (0.004)*** & (0.002)***\\
$\beta_1$ & 0.095 & 0.1 & -0.155 & 0 & 0.072 & 0.06 & 0.078 & 0.068\\
 & (0.011)*** & (0.011)*** & (0.011)*** & (0.01) & (0.008)*** & (0.013)*** & (0.008)*** & (0.004)***\\
$\beta_2$ & 0.899 & 0.9 & 0.982 & 0.902 & 0.928 & 0.787 & 0.922 & 0.899\\
 & (0.011)*** &  & (0)*** & (0.013)*** &  & (0.022)*** & (0.009)*** & (0)***\\
\addlinespace
$\xi$ & 0.918 & 0.918 & 0.89 & 0.895 & 0.915 & 0.885 & 0.891 & 0.885\\
 & (0.017)*** & (0.017)*** & (0.017)*** & (0.016)*** & (0.016)*** & (0.017)*** & (0.017)*** & (0.017)***\\
$\eta$ & 3.301 & 3.153 & 3.95 & 3.868 & 3.624 & 4.062 & 4.0335 & 4.0635\\
 & (0.325)*** & (0.273)*** & (0.4355)*** & (0.422)*** & (0.285)*** & (0.46)*** & (0.451)*** & (0.457)***\\
$\gamma$ &  &  & 0.107 & 0.177 &  &  &  & \\
\addlinespace
 &  &  & (0.011)*** & (0.02)*** &  &  &  & \\
$shift$ &  &  &  &  &  & 1.567 &  & 0.393\\
 &  &  &  &  &  & (0.332)*** &  & (0.014)***\\
$rot$ &  &  &  &  &  &  & 1 & 1\\
 &  &  &  &  &  &  & (0.069)*** & (0.117)***\\
\addlinespace
$LLH$ & -8303.694 & -8304.437 & -8158.11 & -8186.06 & -8328.667 & -8143.563 & -8154.785 & -8143.141\\
\bottomrule
\end{tabular}}
\begin{tablenotes}
\item \textit{Notes:} 
\item This table shows the maximum likelihood estimates of various ST-GARCH models. The daily returns used on the Euro Stoxx 50 cover the period from 03 January, 2001 to 19 May, 2021 (5316 observations).
\item The mean process is modeled as follows: $R_t= \alpha_0+ \alpha_1 \times R_{t-1}+ \varepsilon_t$ Where, in the 8 GARCH models estimated, $\gamma$ is the asymmetry in volatility, $\xi, \kappa$ and $\eta$ are constant and robust standard errors based on the method of White (1982)) are displayed in parenthesis. $LLH$ is the maximized log likelihood value.
\end{tablenotes}
\end{threeparttable}
\end{table}
\end{landscape}

\clearpage
\newpage

\begin{landscape}\begin{table}

\caption{\label{tab:Table3b}Maximum likelihood estimates of the SGED-GARCH models with constant skewness and kurtosis parameters}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllllll}
\toprule
 & SGARCH & IGARCH & EGARCH & GJRGARCH & EWMA & NAGARCH & TGARCH & AVGARCH\\
\midrule
$\alpha_0$ & 0.046 & 0.045 & 0.008 & 0.014 & 0.046 & 0 & 0.007 & -0.002\\
 & (0.011)*** & (0.012)*** & (0.008) & (0.012) & (0.015)*** & (0.008) & (0.012) & (0.012)\\
$\alpha_1$ & -0.055 & -0.055 & -0.041 & -0.05 & -0.056 & -0.043 & -0.047 & -0.041\\
 & (0.013)*** & (0.014)*** & (0.012)*** & (0.013)*** & (0.016)*** & (0.012)*** & (0.011)*** & (0.012)***\\
$\beta_0$ & 0.02 & 0.015 & 0.005 & 0.023 & 0 & 0.025 & 0.024 & 0.025\\
\addlinespace
 & (0.005)*** & (0.004)*** & (0.002)** & (0.004)*** &  & (0.003)*** & (0.005)*** & (0.002)***\\
$\beta_1$ & 0.096 & 0.104 & -0.151 & 0 & 0.07 & 0.059 & 0.077 & 0.067\\
 & (0.012)*** & (0.012)*** & (0.01)*** & (0.01) & (0.008)*** & (0.007)*** & (0.01)*** & (0.003)***\\
$\beta_2$ & 0.895 & 0.896 & 0.981 & 0.901 & 0.93 & 0.793 & 0.922 & 0.897\\
 & (0.012)*** &  & (0)*** & (0.014)*** &  & (0.009)*** & (0.01)*** & (0)***\\
\addlinespace
$\xi$ & 0.935 & 0.936 & 0.901 & 0.906 & 0.93 & 0.896 & 0.902 & 0.896\\
 & (0.021)*** & (0.023)*** & (0.019)*** & (0.02)*** & (0.02)*** & (0.017)*** & (0.019)*** & (0.018)***\\
$\eta$ &  &  &  &  &  &  &  & \\
 &  &  &  &  &  &  &  & \\
$\gamma$ &  &  & 0.107 & 0.175 &  &  &  & \\
\addlinespace
 &  &  & (0.01)*** & (0.021)*** &  &  &  & \\
$shift$ &  &  &  &  &  & 1.547 &  & 0.435\\
 &  &  &  &  &  & (0.147)*** &  & (0.012)***\\
$rot$ &  &  &  &  &  &  & 1 & 0.959\\
 &  &  &  &  &  &  & (0.076)*** & (0.101)***\\
\addlinespace
$LLH$ & -8300.515 & -8302.804 & -8164.576 & -8189.218 & -8330.811 & -8149.596 & -8160.239 & -8149.518\\
\bottomrule
\end{tabular}}
\begin{tablenotes}
\item \textit{Notes:} 
\item This table shows the maximum likelihood estimates of various SGED-GARCH models. The daily returns used on the Euro Stoxx 50 Price index cover the period from 03 January, 2001 to 19 May, 2021 (5316 observations).
\item The mean process is modeled as follows: $R_t= \alpha_0+ \alpha_1 \times R_{t-1}+ \varepsilon_t$ Where, in the 8 GARCH models estimated, $\gamma$ is the asymmetry in volatility, $\xi, \kappa$ and $\eta$ are constant and robust standard errors based on the method of White (1982)) are displayed in parenthesis. $LLH$ is the maximized log likelihood value.
\end{tablenotes}
\end{threeparttable}
\end{table}
\end{landscape}

\clearpage
\newpage

\noindent To compare the goodness-of-fit of different combinations of GARCH models and distributions, we have portrayed the AICs in table \ref{tab:aicTable}. The smaller the criterium the better. As you can see in table \ref{tab:aicTable} the AIC for the skewed student's t-distribution (ST) is the best for almost all the models. As also shown in appendix part \ref{goodness-of-fit}. Only for the SGARCH and IGARCH the SGED distribution has a lower AIC. The best goodness-of-fit over all distributions seems to be the NAGARCH model.

\noindent  Due to \ref{tab:aicTable} being the result of an in-sample estimation, we will further examine the performance five different GARCH models (EGARCH, GJRGARCH, NAGARCH, AVGARCH and TGARCH).

\begin{table}[h!]

\caption{\label{tab:aicTable}Model selection according to AIC}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lrrrrrrrr}
\toprule
  & SGARCH & IGARCH & EWMA & EGARCH & GJRGARCH & NAGARCH & TGARCH & AVGARCH\\
\midrule
N & 3.174 & 3.176 & 3.198 & 3.114 & 3.124 & 3.107 & 3.111 & 3.107\\
T & 3.130 & 3.130 & 3.140 & 3.079 & 3.089 & 3.074 & 3.077 & 3.074\\
ST & 3.127 & 3.127 & 3.135 & 3.072 & 3.083 & 3.067 & 3.071 & 3.067\\
GED & 3.128 & 3.128 & 3.139 & 3.080 & 3.089 & 3.075 & 3.079 & 3.076\\
SGED & 3.125 & 3.126 & 3.136 & 3.075 & 3.084 & 3.069 & 3.073 & 3.069\\
\bottomrule
\end{tabular}}
\begin{tablenotes}
\item \textit{Notes} 
\item This table shows the AIC value for the respective model. With on the rows the distributions. 
\end{tablenotes}
\end{threeparttable}
\end{table}

\clearpage
\newpage

\hypertarget{value-at-risk-1}{%
\subsection{Value-at-risk}\label{value-at-risk-1}}

\noindent As already mentioned 2 candidate models seem to be very appropriate. This includes the EGARCH and the NAGARCH So to check if they perform well out-of-sample we conduct a backtest by using a rolling forecasting technique. A simple graph is shown in figure \ref{fig:figVaRinsample} for the EGARCH-ST model. It seems that the VaR model for \(\alpha=0.05\) underestimates the downside events, while the VaR model for \(\alpha=0.01\) captures more of the downside events.

\begin{figure}[h]

{\centering \includegraphics[width=0.6\linewidth]{_main_files/figure-latex/figVaRinsample-1} 

}

\caption{Value-at-Risk (in-sample) for the EGARCH-ST model}\label{fig:figVaRinsample}
\end{figure}

\noindent Let us examine this further using a rolling window approach whilst forecasting 1-day ahead results with re-estimating parameters every year.

\noindent Figure \ref{fig:figbacktest} shows that choosing an appropriate forecast period is important (with here the Eurobond crisis, the Brexit and Covid-crisis), so in order to avoid a look-ahead bias this rolling window approach was used instead of a static forecast method. \newpage

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth]{_main_files/figure-latex/figbacktest-1} 

}

\caption{Selected period to start forecast from}\label{fig:figbacktest}
\end{figure}

\noindent If we look at the results of the rolling window, we can for example compare as in figure \ref{fig:figurebacktests2} the EGARCH-ST (with skewed student's t-distribution) with the EGARCH-N (with normal distribution). The EGARCH-N seems to capture the extreme events a bit less compared EGARCH-ST. But let us formally test this.~\\

\newpage

\begin{figure}[h]

{\centering \includegraphics[width=0.9\linewidth]{_main_files/figure-latex/figurebacktests2-1} 

}

\caption{Comparison between VaR-EGARCH-ST and VaR-NAGARCH-N}\label{fig:figurebacktests2}
\end{figure}

With the SGED as underlying distribution, the ratio of actual to expected VaR exceedances is highest for the GJRGARCH model, with an excess exceedance rate of 24\%. The other GARCH models still have a positive but slightly lower excess exceedance rate of 21\%. The ratio of actual to expected CVaR exceedances gives a similar picture, with the highest excess exceedance rate being the GJRGARCH with 25\% and for the other models 21\%. These results are significant at the 5\% level, except for the NAGARCH, which is significant only at the 10\% level. This points that the difference between actual and expected exceedances is significantly different from 0. For all models under the SGED, the unconditional and conditional cover test and the dynamic quantile test statistics are insignificant. This suggests that the SGED is a good distribution for calculating VaR and CVaR.

With the ST as underlying distribution, the ratio of actual to expected VaR exceedances is highest for the TGARCH model, with an excess exceedance rate of 28\%. The NAGARCH model has the lowest VaR excess exceedance rate of 17\%. For the CVaR excess exceedance rate, there is a similar picture, with the TGARCH having an excess exceedance rate of 29\% and the NAGARCH of 18\%. These results are insignificant, thus it cannot be concluded that the excess exceedance for VaR and CVaR are significantly different from 0. Both the unconditional and conditional cover tests are insignificant. However, the dynamic quantile test is significant at the 10\% level for the EGARCH and TGARCH. This suggests that the ST distribution is a good distribution for calculating VaR and CVaR, though not as good as the SGED.

The GED, T and normal distribution have significant unconditional and conditional and dynamic quantile test statistics for most models, which suggest they are less appropriate for modeling VaR and CVaR.

\newpage

\begin{table}

\caption{\label{tab:Table4}VaR and CVaR test statistics}
\centering
\begin{threeparttable}
\begin{tabular}[t]{llllll}
\toprule
  & EGARCH & GJRGARCH & TGARCH & NAGARCH & AVGARCH\\
\midrule
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Panel A: SGED}}\\
\hspace{1em}\hspace{1em}AE VaR & 1.207 & 1.243 & 1.207 & 1.207 & 1.207\\
\hspace{1em}\hspace{1em}AE CVaR & 1.214** & 1.25** & 1.214** & 1.214* & 1.214**\\
\hspace{1em}\hspace{1em}UC & 1.147 & 1.558 & 1.147 & 1.147 & 1.147\\
\hspace{1em}\hspace{1em}CC & 1.979 & 2.439 & 1.979 & 1.979 & 1.979\\
\hspace{1em}\hspace{1em}DQ & 7.757 & 13.286 & 12.578 & 5.223 & 5.846\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Panel B: GED}}\\
\hspace{1em}\hspace{1em}AE VaR & 1.456 & 1.456 & 1.491 & 1.456 & 1.385\\
\hspace{1em}\hspace{1em}AE CVaR & 1.464*** & 1.464** & 1.5*** & 1.464** & 1.393***\\
\hspace{1em}\hspace{1em}UC & 5.184** & 5.184** & 5.969** & 5.184** & 3.764*\\
\hspace{1em}\hspace{1em}CC & 6.396** & 6.396** & 7.242** & 6.396** & 4.859*\\
\hspace{1em}\hspace{1em}DQ & 20.235*** & 16.564** & 19.584** & 11.688 & 10.508\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Panel C: ST}}\\
\hspace{1em}\hspace{1em}AE CVaR & 1.207 & 1.243 & 1.278 & 1.172 & 1.243\\
\hspace{1em}\hspace{1em}AE CVaR & 1.214 & 1.25 & 1.286 & 1.179 & 1.25\\
\hspace{1em}\hspace{1em}UC & 1.147 & 1.558 & 2.026 & 0.796 & 1.558\\
\hspace{1em}\hspace{1em}CC & 1.979 & 2.439 & 2.959 & 1.579 & 2.439\\
\hspace{1em}\hspace{1em}DQ & 15.071* & 13.002 & 13.935* & 4.552 & 6.841\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Panel D: T}}\\
\hspace{1em}\hspace{1em}AE VaR & 1.527 & 1.562 & 1.562 & 1.491 & 1.598\\
\hspace{1em}\hspace{1em}AE CVaR & 1.536 & 1.571 & 1.571* & 1.5 & 1.607\\
\hspace{1em}\hspace{1em}UC & 6.803*** & 7.683*** & 7.683*** & 5.969** & 8.61***\\
\hspace{1em}\hspace{1em}CC & 8.137** & 9.081** & 9.081** & 7.242** & 10.072***\\
\hspace{1em}\hspace{1em}DQ & 0.012 & 18.986** & 22.759*** & 17.376** & 25.561***\\
\addlinespace[0.3em]
\multicolumn{6}{l}{\textbf{Panel E: N}}\\
\hspace{1em}\hspace{1em}AE VaR & 1.953 & 1.882 & 1.953 & 1.74 & 1.776\\
\hspace{1em}\hspace{1em}AE CVaR & 1.964*** & 1.893*** & 1.964*** & 1.75*** & 1.786***\\
\hspace{1em}\hspace{1em}UC & 20.217*** & 17.575*** & 20.217*** & 12.76*** & 13.904***\\
\hspace{1em}\hspace{1em}CC & 22.409*** & 19.609*** & 22.409*** & 14.496*** & 15.712***\\
\hspace{1em}\hspace{1em}DQ & 36.498*** & 32.87*** & 39.472*** & 27.102*** & 37.614***\\
\bottomrule
\end{tabular}
\begin{tablenotes}
\item \textit{Notes:} 
\item Table contains the ratio of actual to expected exceedances for VaR and Conditional VaR, the unconditional and conditional coverage test statistic and the dynamic quantile test statistic for VaR. Significance levels for the VaR ratio not reported. *, ** and *** point out significance at 10, 5 and 1 percent level.
\end{tablenotes}
\end{threeparttable}
\end{table}

\clearpage

\hypertarget{time-varying-higher-moments}{%
\section{Time-varying higher moments}\label{time-varying-higher-moments}}

As we already pointed out in part \ref{lit-rev}, it might also be interesting to look at time-varying moments and check if there is an improvement for estimating the VaR and CVaR as \textcite{bali2008} did for example.

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Notes:} 
\item This table shows the maximum likelihood estimates of various SGED-GARCH models. The daily returns used on the Euro Stoxx 50 Price index cover the period from 03 January, 2001 to 19 May, 2021 (5316 observations).
\item The mean process is modeled as follows: $R_t= \alpha_0+ \alpha_1 \times R_{t-1}+ \varepsilon_t$ Where, in the model estimated, $\gamma$ is the asymmetry in volatility,  (calculated using robust standard errors based on the method of White (1982)) are displayed in parenthesis.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedright}X}
\caption{\label{tab:Table5}Maximum likelihood estimates of the ST-ACD model with constant skewness and kurtosis parameters}\\
\toprule
  & ACD GARCH\\
\midrule
$\alpha_0$ & 0.054   (0.111)\\
$\alpha_1$ & -0.044   (0.216)\\
$\beta_0$ & 0.02\\
$\beta_1$ & 0.098   (0.002)***\\
$\beta_2$ & 0.892   (0.009)***\\
\addlinespace
$\chi_0$ & -1.548   (13.208)\\
$\chi_1$ & 0.046   (0.401)\\
$\chi_2$ & 0.032   (0.488)\\
$\xi_1$ & 0.563   (3.778)\\
$\kappa_{0}$ & 0.127   (0.196)\\
\addlinespace
$\kappa_{1}$ & 0   (0.175)\\
$\kappa_{2}$ & 1   (0.249)***\\
$\psi_{1}$ & 0.788   (0.101)***\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}

The following figure \ref{fig:figureACDmoments} plots the conditional mean, the conditional volatility. The implied conditional time varying skewness and excess kurtosis for the Euro Stoxx 50 series.

\begin{figure}[h]

{\centering \includegraphics{_main_files/figure-latex/figureACDmoments-1} 

}

\caption{Dynamics of the ACD model}\label{fig:figureACDmoments}
\end{figure}

\newpage

\noindent After performing a backtest\footnote{This backtest contains the following features: recursive, window of 2500, refitted every 250 trading days (approximately one year).}, we observe that the ACD model is slightly worse than the GARCH equivalent in estimating the VaR. Although there are much less models tested here because of the difficulty of the procedure of ACD models, we find less convincing evidence of the merit of using conditional higher moments in VaR and CVaR estimation. So contrary to \textcite{bali2008}, we find that the ACD models seem to underperform to the GARCH model. With a rejection of unconditional coverage test statistic at 10\% significance level. It is not surprising that the GARCH model performs bad as well looking at the rejection of the dynamic quantile test and the CVaR test.

\newpage

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Notes:} 
\item Table contains the ratio of actual to expected exceedances for VaR and Expected Shortfall, the unconditional and conditional coverage test statistic and the dynamic quantile test statistic for VaR. Significance levels for the VaR ratio not reported. *, ** and *** point out significance at 10, 5 and 1 percent level.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\caption{\label{tab:tableACDBacktest}VaR and ES test statistics (ACD-ST vs GARCH-ST)}\\
\toprule
  & ACD & GARCH\\
\midrule
AE VaR & 1.357 & 1.286\\
AE CVaR & 1.357** & 1.286**\\
UC & 3.131* & 2.026\\
CC & 4.171 & 2.959\\
DQ & 16.118** & 14.587*\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}

\hypertarget{Robustness}{%
\chapter{Robustness checks}\label{Robustness}}

\noindent In order to check if the models are specified correctly, some diagnostic checks have to be performed. The specification checks have to be done on the standardized residuals of the estimated GARCH model given by the following equation: \[ \hat{Z_t} = \dfrac{\hat{\varepsilon_t}}{\hat{\sigma_t}} = \dfrac{R_t - \hat{\mu}}{\hat{\sigma_t}}\].

Table \ref{tab:LjboxTable} Panel A displays the Ljung-box test on the squared standardized residuals of the GARCH models. Panel B displays the ARCH LM test on the squared standardized residuals. The ARCH LM test checks if the ARCH process is adequately fitted.

The description of table

\begin{landscape}\begin{table}[h!]

\caption{\label{tab:LjboxTable}Diagnostic Tests for Heteroscedasticity}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllllll}
\toprule
  & SGARCH & EGARCH & AVGARCH & NAGARCH & GJRGARCH & TGARCH & IGARCH & EWMA\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel A: Ljung Box Test on the standardized squared values of the residuals}}\\
\hspace{1em}Norm & 31.157* & 25.321 & 22.263 & 23.03 & 32.186* & 26.208 & 32.727* & 44.066***\\
\hspace{1em}T & 33.907** & 24.81 & 21.321 & 21.862 & 34.34** & 26.658 & 34.183** & 41.765***\\
\hspace{1em}ST & 33.961** & 25.024 & 21.412 & 22.051 & 34.607** & 26.811 & 34.187** & 40.605***\\
\hspace{1em}GED & 32.493* & 24.826 & 21.63 & 22.191 & 33.365* & 26.142 & 33.361* & 42.627***\\
\hspace{1em}SGED & 32.569* & 25.065 & 21.57 & 22.341 & 33.747* & 26.351 & 33.342* & 41.333***\\
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel B: ARCH LM Test on the standardized squared values of the residuals}}\\
\hspace{1em}Norm & 32.322* & 26.461 & 23.081 & 23.474 & 34.475** & 26.991 & 33.857* & 42.773***\\
\hspace{1em}T & 34.687** & 25.958 & 22.063 & 22.218 & 37.875** & 27.634 & 34.912** & 40.719***\\
\hspace{1em}ST & 34.605** & 26.138 & 22.129 & 22.36 & 38.174** & 27.718 & 34.756** & 39.559**\\
\hspace{1em}GED & 33.431* & 25.973 & 22.433 & 22.598 & 36.379** & 27.023 & 34.228** & 41.433***\\
\hspace{1em}SGED & 33.393* & 26.173 & 22.319 & 22.698 & 36.859** & 27.167 & 34.071** & 40.155***\\
\bottomrule
\end{tabular}}
\begin{tablenotes}
\item \textit{Notes} 
\item Table displays the Ljung box statistics and the ARCH LM Test for the standardized squared residuals of the models analyzed. The underlying data is the daily return series of the Euro Stoxx 50 for the period between 2001-01-03 and 2021-05-19.
\item *, ** and *** point out respectively significance at 10, 5 and 1 percent level.
\item The null hypothesis of the test in both panels are described as follows:
\item $H_0$: $Corr$($Z_t^2$,$Z_{t-1}^2$)=$Corr$($Z_t^2$,$Z_{t-2}^2$)= $...$ =$Corr$($Z_t^2$,$Z_{t-22}^2$) = $0$
\end{tablenotes}
\end{threeparttable}
\end{table}
\end{landscape}

The Generalized Method of Moments (GMM) test by \textcite{hansen1982} is also a test that checks if the model is correctly specified or not. Here only the results of the t-tests for the four individual moments are examined from the GMM test\footnote{We already looked at the joint conditional moment: serial correlation in the squares or in the variances}. The mean (first moment) should be equal to zero (or or \(E\left[z_{t}\right]=0\)). The variance (second moment) should be equal to one (or \(E\left[z_{t}^2-1\right]=0\)). The skewness should be equal to zero and the excess kurtosis (third and fourth moment) should be equal to zero ( respectively \(E\left[z_{t}^3\right]=0\) and \(E\left[z_{t}^4-3\right] = 0\)).

\begin{landscape}\begin{table}[h!]

\caption{\label{tab:GMMtable}GMM Tests}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllllll}
\toprule
  & SGARCH & EGARCH & AVGARCH & NAGARCH & GJRGARCH & TGARCH & IGARCH & EWMA\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel A: SGED}}\\
\hspace{1em}Mean & -0.036** & -0.002 & 0.007 & 0.006 & -0.006 & -0.001 & -0.036** & -0.039***\\
\hspace{1em}Variance & 0.015** & 0.009 & 0.007 & 0.007 & 0.01 & 0.008 & -0.016** & 0.121***\\
\hspace{1em}Skewness & -0.46** & -0.392 & -0.374 & -0.381 & -0.406 & -0.374 & -0.443** & -0.566***\\
\hspace{1em}Excess Kurtosis & 1.974** & 1.782 & 1.809 & 1.803 & 1.693 & 1.696 & 1.755** & 3.821***\\
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel B: GED}}\\
\hspace{1em}Mean & -0.051*** & -0.024* & -0.015 & -0.017 & -0.026* & -0.022 & -0.05*** & -0.051***\\
\hspace{1em}Variance & 0.004*** & 0.004* & 0.004 & 0.004 & 0.003* & 0.003 & -0.024*** & 0.12***\\
\hspace{1em}Skewness & -0.49*** & -0.452* & -0.438 & -0.444 & -0.459* & -0.435 & -0.476*** & -0.602***\\
\hspace{1em}Excess Kurtosis & 1.858*** & 1.763* & 1.815 & 1.809 & 1.662* & 1.689 & 1.661*** & 3.824***\\
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel C: ST}}\\
\hspace{1em}Mean & -0.042*** & -0.009 & 0.002 & 0.001 & -0.012 & -0.007 & -0.042*** & -0.049***\\
\hspace{1em}Variance & 0.006*** & 0.005 & 0.003 & 0.003 & 0.004 & 0.005 & -0.016*** & 0.124***\\
\hspace{1em}Skewness & -0.473*** & -0.414 & -0.388 & -0.396 & -0.421 & -0.393 & -0.46*** & -0.596***\\
\hspace{1em}Excess Kurtosis & 1.944*** & 1.79 & 1.809 & 1.808 & 1.671 & 1.702 & 1.777*** & 3.855***\\
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel D: T}}\\
\hspace{1em}Mean & -0.059*** & -0.03** & -0.019 & -0.02 & -0.032** & -0.027* & -0.059*** & -0.062***\\
\hspace{1em}Variance & -0.007*** & 0.001** & 0.003 & 0.002 & -0.001** & 0.002* & -0.024*** & 0.124***\\
\hspace{1em}Skewness & -0.511*** & -0.473** & -0.452 & -0.458 & -0.476** & -0.451* & -0.501*** & -0.638***\\
\hspace{1em}Excess Kurtosis & 1.812*** & 1.783** & 1.848 & 1.84 & 1.658** & 1.707* & 1.674*** & 3.856***\\
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{Panel E: N}}\\
\hspace{1em}Mean & -0.051*** & -0.007 & 0.004 & 0.002 & -0.01 & -0.004 & -0.051*** & -0.047***\\
\hspace{1em}Variance & 0.001*** & 0.001 & 0 & 0 & 0.001 & 0 & -0.035*** & 0.118***\\
\hspace{1em}Skewness & -0.482*** & -0.391 & -0.371 & -0.378 & -0.405 & -0.372 & -0.465*** & -0.583***\\
\hspace{1em}Excess Kurtosis & 1.775*** & 1.684 & 1.736 & 1.721 & 1.605 & 1.616 & 1.516*** & 3.807***\\
\bottomrule
\end{tabular}}
\begin{tablenotes}[para]
\item \textit{Notes} 
\item Table displays the GMM test statistics for the standardized residuals. The underlying data is the daily return series of the Euro Stoxx 50 for the period between 2001-01-03 and 2021-05-19.
\item The null hypothesis of the test for each variable are described as follows: $H_0: $ $E[z_{t}] = 0$ for the mean, $H_0: $ $E[z_{t}^2-1] = 0$ for the variance. $H_0: $ $E[z_{t}^3] = 0$ for the skewness and $H_0: $ $E[z_{t}^4-3] = 0$ for the excess kurtosis.
\end{tablenotes}
\end{threeparttable}
\end{table}
\end{landscape}

\begin{landscape}\begin{table}[h!]

\caption{\label{tab:JBTable}Jarque-Bera Test on standardized residuals}
\centering
\begin{threeparttable}
\resizebox{\linewidth}{!}{
\begin{tabular}[t]{lllllllll}
\toprule
  & SGARCH & EGARCH & AVGARCH & NAGARCH & GJRGARCH & TGARCH & IGARCH & EWMA\\
\midrule
Norm & 739.888*** & 735.992*** & 791.977*** & 784.475*** & 676.533*** & 679.569*** & 804.423*** & 1382.222***\\
T & 822.929*** & 789.877*** & 839.862*** & 845.41*** & 703.17*** & 718.176*** & 851.465*** & 1350.929***\\
ST & 845.468*** & 787.192*** & 833.066*** & 842.468*** & 700.469*** & 712.976*** & 884.557*** & 1360.366***\\
GED & 785.374*** & 759.794*** & 810.002*** & 811.834*** & 685.775*** & 697.098*** & 841.477*** & 1367.132***\\
SGED & 803.315*** & 758.538*** & 810.37*** & 811.343*** & 684.155*** & 691.427*** & 869.762*** & 1372.361***\\
\bottomrule
\end{tabular}}
\begin{tablenotes}[para]
\item \textit{Notes} 
\item Table displays the Jarque-Bera statistic $JB=\frac{n}{6}(S^{2}+\frac{1}{4}(K-3)^{2})$ with $n$ the sample size, $K$ the kurtosis and $S$ the skewness for the residuals of the models. The JB statistic is distributed $\chi^2$ with $\nu = 2$. The underlying data is the daily return series of the Euro Stoxx 50 for the period between 2001-01-03 and 2021-05-19.
\item *, ** and *** point out respectively significance at 10, 5 and 1 percent level.
\item The null hypothesis is that $S$ and $K$ are not significantly different than what would be found under normality (0 and 3).
\end{tablenotes}
\end{threeparttable}
\end{table}
\end{landscape}

\footnote{Note that using monthly returns instead of daily, it cannot be rejected that the residuals are normally distributed.}

DESCRIPTION GRAPHS

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth]{_main_files/figure-latex/figuresqq-1} 

}

\caption{QQ plots of AVGARCH residuals versus the standardized returns of the series}\label{fig:figuresqq}
\end{figure}

\hypertarget{Conclusion}{%
\chapter{Conclusion}\label{Conclusion}}

This paper tested whether including higher-order moments in VaR and cVaR would make for more accurate risk measurement. The starting point for this was that there is a strong body of literature that suggests market returns are leptokurtotic and right-skewed. We chose to focus on daily data and forecast one period ahead, as this is the most relevant for short-term trading desks and the requirements of regulators.

Inspired by Bali, we selected 5 different distributions and 8 different GARCH models, for a total of 40 combinations, to estimate VaR and cVaR. We used daily data from the Eurostoxx 50 log return index between 2001 and 2021, a period which includes both major market crises from the 21th century: the Global Financial Crisis and the Covid-19 pandemic.

Our studied distributions are all limiting cases of the SGT-distribution studied by Bali, namely the SGED, GED, ST, T and Normal distribution. To provide some intuition on which distributions most closely match the observed log returns, we performed maximum likelihood estimation and compared the Aikaike Information Criterions to penalize complexity. We found that the SGED distribution is as good as the SGT (due to having one less parameter to estimate, even though it fits the data slightly worse). The normal distribution fitted the observed returns the worst, with both the maximum likelihood score and the AIC underperforming the other distributions. This affirmed previous literature that the normal distribution is inadequate to model returns.

As a second step we estimated the 8 GARCH models (SGARCH, IGARCH, EGARCH, EWMA, GJRGARCH, NAGARCH, TGARCH and AVGARCH) with the 5 underlying distributions in-sample and again reported the AIC. We found that the best model to forecast 1 day returns was the AVGARCH-ST. The ST distribution is generally the most performant over all GARCH models, with SGED being slightly better only for the SGARCH and IGARCH.

In a third step, we reported on the parameters of the different GARCH models for these two distributions, and find that the skewness and shape parameters are highly significant, suggesting that indeed higher order moments are relevant for estimating VaR and cVaR.

To avoid look-ahead bias as introduced by in-sample estimation, we applied a rolling window technique to 25 combinations (selecting the 5 best GARCH models on the basis of AIC). Here we refitted every 22 trading days and forecast 1 trading day. Subsequently we computed the VaR and cVaR and compared results for 4 performance tests: the ESTest \textcite{Mcneil}, Unconditional Coverage test, Conditional Coverage test and Dynamic Quantile test. We found that the smallest difference between predicted and actual exceedances over the \(VaR_{0.01}\) was for the NAGARCH-ST. For most other models the SGED distribution has the smallest difference. For the \(cVaR_{0.01}\) and associated ESTest, the results are that the SGED distribution gives the smallest difference between predicted and actual exceedances for the TGARCH and the AVGARCH and the same as the ST distribution for EGARCH and GJRGARCH. For both distributions, the uc, cc and dq are insignificant. The other distributions have significant values for the cc and uc test and for the most part for the dq test and are thus not as suitable for (c)VaR estimation.

To our knowledge, there has been little research on including time-varying moments beyond the variance in (c)VaR estimation. We allow for skewness and shape parameters to vary using an ACD model as proposed by \textcite{Ghalanos}. We compared the results of the SGARCH model with the ACD model and concluded that allowing higher moments to vary over time gives better goodness-of-fit in terms of maximum log-likelihood and AIC and more parameters (especially the shape parameter) significant. However it did not improve the (c)VaR estimation for any of the 4 performance tests. Future research might study ACD models for different GARCH models, than the standard one, better (c)VaR tests.

We performed 4 different robustness checks on the in-sample GARCH estimations to test if the residuals are normally distributed. First, we performed the Ljung-Box Test on the residuals and reject the null-hypothesis that there is no serial correlation of variance. Second, we applied the ARCH LM test on absolute, and squared residuals of our GARCH models and came to the same conclusion as with the Ljung-Box test (these are similar tests, except that the former tests the ARMA process and the latter the ARCH process). Third, we performed the GMM test to see if the residuals have moments equal to those of of the normal distribution. We find that this hypothesis can be rejected with high significance. Last, we performed the Jarque-Bera test to test if the kurtosis and skewness matches the normal distribution. We reject this hypothesis as well. There is thus ample evidence that the residuals are non-normal.

To study the external validity of our research, we also applied our methodology to 3 further datasets: the Eurostoxx 50 Price index (which goes back to 1987), CAC40 return index, BEL20 return index and FTSE100 return index, to estimate if the combination of models and distribution we found to be the most efficient models to calculate (c)VaR over a wide range of European markets stays the same. We found that XXX.

Different scenarios of ARMA order variation suggest that this does not affect results as much as the distribution or GARCH model choice.

To conclude by answering the research question ``Do higher moments increase accuracy in the estimation of VaR and cVaR?'', we can answer in the positive, though caution that more model complexity might not always mean better VaR and cVaR estimation.

\startappendices

\hypertarget{appendix-to-literature-review}{%
\chapter{Appendix to literature review}\label{appendix-to-literature-review}}

\hypertarget{conditional-distributions}{%
\subsubsection{Alternatives to the normal distribution}\label{conditional-distributions}}

\hypertarget{sgtinfo}{%
\subparagraph{SGT (Skewed Generalized t-distribution)}\label{sgtinfo}}

\noindent The SGT distribution is introduced by \textcite{theodossiou1998} and applied by \textcite{bali2007} and \textcite{bali2008}. According to \textcite{bali2008} the proposed solutions (use of historical simulation, student's t-distribution, generalized error distribution or a mixture of two normal distributions) to the non-normality of standardized financial returns only partially solved the issues of accounting for skewness and leptokurtosis.The Pdf of the SGT distribition is given by eqution \eqref{eq:sgt}. B is the beta function (also called Euler integral).

\begin{equation}
\begin{array}{c}
\begin{array}{c}
f_{S G T}(x ; \mu, \sigma, \xi, \kappa, \eta)=\frac{\kappa}{2 v \sigma \eta^{1 / \kappa} B\left(\frac{1}{\kappa}, \eta\right)\left(\frac{|x-\mu +m|^{\kappa}}{\eta(v \sigma)^{\kappa}(\xi \operatorname{sign}(x-\mu + m)+1)^{\kappa}}+1\right)^{\frac{1}{\kappa}+\eta}} \\ \\ \\ 

m=\frac{2 v \sigma \xi \eta^{\frac{1}{\kappa}} B\left(\frac{2}{\kappa}, \eta-\frac{1}{\kappa}\right)}{B\left(\frac{1}{\kappa}, \eta\right)}
\end{array}
\\ \\ \\ 
v=\frac{\eta^{-\frac{1}{\kappa}}}{\sqrt{\left(3 \xi^{2}+1\right) \frac{B\left(\frac{3}{\kappa}, \eta-\frac{2}{\kappa}\right)}{B\left(\frac{1}{\kappa}, \eta\right)}-4 \xi^{2} \frac{B\left(\frac{2}{\kappa}, \eta-\frac{1}{\kappa}\right)^{2}}{B\left(\frac{1}{\kappa}, \eta\right)^{2}}}}
\end{array}
\label{eq:sgt}
\end{equation}

\noindent Following \textcite{theodossiou1998} however, there are two parameters, \(\kappa\)\footnote{Referred to as \(\kappa\) by \textcite{theodossiou1998} and \textcite{bali2008}, but \(p\) by Carter Davis in the ``sgt'' package.}and \(\eta\)\footnote{Also referred to as \(n\) by \textcite{theodossiou1998} and \(\eta\) by \textcite{bali2008}, but \(q\) by Carter Davis in the ``sgt'' packages.}) for the shape in the SGT distribution. \(\kappa\) is the peakedness parameter. \(\eta\) is the tail-thickness parameter. It is equal to the degrees of freedom \(\nu\) divided by 2 if \(\xi = 0\) and \(\kappa = 2\). As shown in the following figure\footnote{Source: \href{https://cran.r-project.org/web/packages/sgt\%22}{https://cran.r-project.org/web/packages/sgt}} \ref{fig:figure} by Carter Davis, from the SGT the other distributions in the figure are limiting cases of the SGT.

\begin{figure}

{\centering \includegraphics[width=1\linewidth]{front-and-back-matter/images/SGT} 

}

\caption{SGT distribution and limiting cases}\label{fig:figure}
\end{figure}

\hypertarget{students-t-distribution}{%
\subparagraph{Student's t-distribution}\label{students-t-distribution}}

\noindent A common alternative for the normal distribution is the Student t distribution. Similarly to the normal distribution, it is also symmetric (skewness is equal to zero if \(\nu > 3\)). The probability density function (pdf), consistent with \textcite{ghalanos2020}, is given by equation \eqref{eq:stdghalanos}. As will be seen in \ref{vol-mod}, GARCH models are used for volatility modeling in practice. \textcite{bollerslev1987} examined the use of the GARCH-Student or GARCH-t model as an alternative to the standard Normal distribution, which relaxes the assumption of conditional normality by assuming the standardized innovation to follow a standardized Student t-distribution \autocite{bollerslev2008}.

\begin{align}
f(x; \mu, \sigma,\nu) = \dfrac{\Gamma(\dfrac{\nu+1}{2})}{\Gamma(\dfrac{\nu}{2})\sqrt{\sigma \pi \nu}} \left(1+\dfrac{(x-\mu)^2}{\sigma \nu}\right)^{-(\nu+1)/2}
 \label{eq:stdghalanos}
\end{align}

\noindent where \(\mu, \sigma\) and \(\nu\) are respectively the mean, scale and shape (tail-thickness) parameters. \(\nu/2\) is equal to the \(\eta\)\footnote{Also referred to as \(n\) by \textcite{theodossiou1998} or \(q\) by Carter Davis in the ``sgt'' package.} parameter of the SGT distribution with other restrictions (see part \ref{sgtinfo}). The symbol \(\Gamma\) is the Gamma function.

\noindent Unlike the normal distribution, which depends on two parameters only, the student t distribution allows for fatter tails. This kurtosis coefficient is given by equation \eqref{eq:kurt} if \(\nu>4\). This is useful while the standardized residuals of stock returns appear to have fatter tails than the normal distribution following \textcite{bollerslev2008}.

\begin{align}
kurt = 3 + \dfrac{6}{\nu-4}
 \label{eq:kurt}
\end{align}

\hypertarget{generalized-error-distribution}{%
\subparagraph{Generalized Error Distribution}\label{generalized-error-distribution}}

\noindent The GED distribution is nested in the generalized t distribution by \textcite{mcdonald1988} and is used in the GED-GARCH model by \textcite{nelson1991} to model stock market returns. This model replaced the assumption of conditional normally distributed error terms by standardized innovations that following a generalized error distribution. It is a symmetric, uni-modal distribution (location parameter is the mode, median and mean). This is also sometimes called the exponential power distribution \autocite{bollerslev2008}. The conditional density (pdf) is given by equation \eqref{eq:ged} following \textcite{ghalanos2020}.

\begin{align}
f(x; \mu, \sigma, \kappa) = \dfrac{\kappa e^{-\frac{1}{2}\left|\dfrac{x-\mu}{\sigma}\right|^\kappa}}{2^{1+1/\kappa}\sigma\Gamma(1/\kappa)}
 \label{eq:ged}
\end{align}

where \(\mu, \sigma\) and \(\kappa\) are respectively the mean, scale and shape parameters.

\hypertarget{skewed-t-distribution}{%
\subparagraph{Skewed t-distribution}\label{skewed-t-distribution}}

\noindent The density function can be derived following \textcite{fernández1998} who showed how to introduce skewness into uni-modal standardized distributions \autocite{trottier2015}. The first equation from \textcite{trottier2015}, here equation \eqref{eq:skeweddist} presents the skewed t-distribution.

\begin{align}
f_{\xi}(z) \equiv \frac{2 \sigma_{\xi}}{\xi+\xi^{-1}} f_{1}\left(z_{\xi}\right), \quad z_{\xi} \equiv\left\{\begin{array}{ll}
\xi^{-1}\left(\sigma_{\xi} z+\mu_{\xi}\right) & \text { if } z \geq-\mu_{\xi} / \sigma_{\xi} \\
\xi\left(\sigma_{\xi} z+\mu_{\xi}\right) & \text { if } z<-\mu_{\xi} / \sigma_{\xi}
\end{array}\right.
 \label{eq:skeweddist}
\end{align}

\noindent where \(\mu_{\xi} \equiv M_{1}\left(\xi-\xi^{-1}\right), \quad \sigma_{\xi}^{2} \equiv\left(1-M_{1}^{2}\right)\left(\xi^{2}+\xi^{-2}\right)+2 M_{1}^{2}-1, \quad M_{1} \equiv 2 \int_{0}^{\infty} u f_{1}(u) d u\) and \(\xi\) between \(0\) and \(\infty\). \(f_1(\cdot)\) is in this case equation \eqref{eq:stdghalanos}, the pdf of the student t distribution coming to equation \eqref{eq:stdist}, which has the parameterization following the SGT parameters.

\begin{equation}
\begin{array}{c}f_{S T}(x ; \alpha, \beta, \xi, \eta)=\frac{\Gamma\left(\frac{1}{2}+\eta\right)}{\sqrt{\beta\pi \eta} \Gamma(\eta)\left(\frac{|x-\alpha+m|^{2}}{\eta\beta(\xi \operatorname{sign}(x-\alpha+m)+1)^{2}}+1\right)^{\frac{1}{2}+\eta}} \\ \\ \\ m=\frac{2 \xi \sqrt{\beta\eta} \Gamma\left(\eta-\frac{1}{2}\right)}{\sqrt{\pi} \Gamma\left(\eta+\frac{1}{2}\right)}\end{array}
 \label{eq:stdist}
\end{equation}

\noindent According to \textcite{giot2003} as well as \textcite{giot2004}, the skewed t-distribution outperforms the symmetric density distributions.

\hypertarget{skewed-generalized-error-distribution}{%
\subparagraph{Skewed Generalized Error Distribution}\label{skewed-generalized-error-distribution}}

\noindent A further distribution to analyse is the SGED distribution of \textcite{theodossiou2000}. It is applied in GARCH models by \textcite{lee2008}. The SGED distribution extends the Generalized Error Distribution (GED) to allow for skewness and leptokurtosis. The density function can be derived following \textcite{fernández1998} who showed how to introduce skewness into uni-modal standardized distributions \autocite{trottier2015}. It can also be found in \textcite{theodossiou2000}. The pdf is then given by the same equation \eqref{eq:skeweddist} as the skewed t-distribution but with \(f_1(\cdot)\) equal to equation \eqref{eq:ged}. To then get equation \eqref{eq:sged}.

\begin{equation}
\begin{array}{c}f_{S G E D}(x ; \mu, \sigma, \xi, \kappa)=\frac{\kappa e^{-\left(\frac{|x-\mu+m|}{v \sigma(1+\xi \operatorname{sig}(x-\mu+m))}\right)^{\kappa}}}{2 \nu \sigma \Gamma(1 / \kappa)} \\ \\ \\ m=\frac{2^{\frac{2}{\kappa}} \nu \sigma \xi \Gamma\left(\frac{1}{2}+\frac{1}{\kappa}\right)}{\sqrt{\pi}} \\ \\ \\ v=\sqrt{\frac{\pi \Gamma\left(\frac{1}{\kappa}\right)}{\pi\left(1+3 \xi^{2}\right) \Gamma\left(\frac{3}{\kappa}\right)-16^{\frac{1}{\kappa}} \xi^{2} \Gamma\left(\frac{1}{2}+\frac{1}{\kappa}\right)^{2} \Gamma\left(\frac{1}{\kappa}\right)}}\end{array}\label{eq:sged}
\end{equation}

\hypertarget{ARCH}{%
\subsubsection{ARCH models}\label{ARCH}}

\noindent From the components of the ARCH model described in part \ref{univ-garch} we could look at the conditional moments (or expected returns and variance). We can plug in the component \(\sigma_t\) into the conditional mean innovation \(\varepsilon_{t}\) and use the conditional mean innovation to examine the conditional mean return. In equation \eqref{eq:eq4} and \eqref{eq:eq5} they are derived. Because the random variable \(z_t\) is distributed with a zero-mean, the conditional expectation is 0. As a consequence, the conditional mean return in equation \eqref{eq:eq5} is equal to the unconditional mean in the most simple case. But variations are possible using ARMA (eg. AR(1)) processes.

\begin{align} 
\mathbb{E}_{t-1}(\varepsilon_{t}) = \mathbb{E}_{t-1}(\sqrt{\beta_0 + \beta_1 \times  \varepsilon_{t-1}^2} \times z_t) = \sigma_t\mathbb{E}_{t-1}(z_t) = 0
 \label{eq:eq4}
\end{align} 

\begin{align} 
\mathbb{E}_{t-1}(y_{t}) = \alpha_0 + \mathbb{E}_{t-1}(\varepsilon_{t}) = \alpha_0
 \label{eq:eq5}
\end{align}

\noindent For the conditional variance, knowing everything that happened until and including period \(t-1\) the conditional innovation variance is given by equation \eqref{eq:eq6}. This is equal to \(\sigma_t^2\), while the variance of \(z_t\) is equal to 1. Then it is easy to derive the conditional variance of returns in equation \eqref{eq:eq7}, that is why equation \eqref{eq:eq3} is called the variance equation.

\begin{align} 
var_{t-1}(\varepsilon_t) = \mathbb{E}_{t-1}(\varepsilon_{t}^2) = \mathbb{E}_{t-1}(\sigma_t^2 \times z_t^2) = \sigma_t^2\mathbb{E}_{t-1}(z_t^2) = \sigma_t^2
 \label{eq:eq6}
\end{align} 

\begin{align} 
var_{t-1}(y_t) = var_{t-1}(\varepsilon_t)= \sigma_t^2
 \label{eq:eq7}
\end{align}

\noindent The unconditional variance is also interesting to derive, while this is the long-run variance, which will be derived in equation \eqref{eq:eq11}. After deriving this using the law of iterated expectations and assuming stationarity for the variance process, one would get equation \eqref{eq:eq8} for the unconditional variance, equal to the constant \(\beta_0\) and divided by \(1-\beta_1\), the slope of the variance equation.

\begin{align} 
\sigma^2 = \dfrac{\beta_0}{1-\beta_1}
 \label{eq:eq8}
\end{align}

\noindent This leads to the properties of ARCH models: Stationarity\footnote{Stationarity implies that the series on which the ARCH model is used does not have any trend and has a constant expected mean. Only the conditional variance is changing.} condition for variance: \(\beta_0>0\) and \(0 \le \beta_1 < 1\). But also, zero-mean innovations and uncorrelated innovations. Thus a weak white noise process \(\varepsilon_t\). The unconditional 4th moment, kurtosis \(\mathbb{E}(\varepsilon_t^4)/\sigma^4\) of an ARCH model is given by equation \eqref{eq:eq9}. This term is larger than 3, which implicates fat-tails.

\begin{align} 
3\dfrac{1-\beta_1^2}{1-3\beta_1^2}
 \label{eq:eq9}
\end{align}

\noindent Another property of ARCH models is that it takes into account volatility clustering. Because we know that \(var(\varepsilon_t) = \mathbb{E}(\varepsilon_t^2) = \sigma^2 = \beta_0/(1-\beta_1)\), we can plug in \(\beta_0\) for the conditional variance \(var_t(\varepsilon_{t+1}) = \mathbb{E}(\varepsilon_{t+1}^2) = \sigma_{t+1}^2 = \beta_0 + \beta_1\times\varepsilon_t^2\). Thus it follows that equation \eqref{eq:eq10} displays volatility clustering. If we examine the RHS, as \(\beta_1>0\) (condition for stationarity), when shock \(\varepsilon_t^2\) is larger than what you expect it to be on average \(\sigma^2\) the LHS will also be positive. Then the conditional variance will be larger than the unconditional variance. Briefly, large shocks will be followed by more large shocks.

\begin{align} 
\sigma_{t+1}^2 - \sigma^2 = \beta_1\times(\varepsilon_t^2 - \sigma^2)
 \label{eq:eq10}
\end{align}

\noindent Excess kurtosis can be modeled, even when the conditional distribution is assumed to be normally distributed. The third moment, skewness, can be introduced using a skewed conditional distribution as we saw in part \ref{conditional-distributions}. The serial correlation for squared innovations is positive if fourth moment exists (equation \eqref{eq:eq9}, this is volatility clustering once again.

\noindent How will then the variance be forecasted? Well, the conditional variance for the \(k\)-periods ahead , denoted as period \(T+k\), is given by equation \eqref{eq:eq11}. This can already be simplified, while we know that \(\sigma_{T+1}^2 = \beta_0 + \beta_1 \times \varepsilon_T^2\) from equation \eqref{eq:eq3}.

\begin{align} 
\begin{split}
\mathbb{E}_T(\varepsilon_{T+k}^2) 
&= \beta_0\times(1+\beta_1 + ... + \beta_1^{k-2}) + \beta_1^{k-1}\times\sigma_{T+1}^2 \\
&= \beta_0\times(1+\beta_1 + ... + \beta_1^{k-1}) + \beta_1^{k}\times\sigma_{T}^2
\end{split}
 \label{eq:eq11}
\end{align}

\noindent It can be shown that then the conditional variance in period \(T+k\) is equal to equation \eqref{eq:eq12}. The LHS is the predicted conditional variance \(k\)-periods ahead above its unconditional variance, \(\sigma^2\). The RHS is the difference current last-observed return residual \(\varepsilon_T^2\) above the unconditional average multiplied by \(\beta_1^k\), a decreasing function of \(k\) (given that \(0 \le\beta_1 <1\)). The further ahead predicting the variance, the closer \(\beta_1^k\) comes to zero, the closer to the unconditional variance, i.e.~the long-run variance.

\begin{align} 
\mathbb{E}_T(\varepsilon_{T+k}^2) - \sigma^2 = \beta_1^k\times(\varepsilon_T^2 - \sigma^2)
 \label{eq:eq12}
\end{align}

\hypertarget{garch-models}{%
\subsubsection{GARCH models}\label{garch-models}}

All the GARCH models are estimated using the package ``rugarch'' by \textcite{alexios2020}. We use specifications similar to \textcite{ghalanos2020}. Parameters have to be restricted so that the variance output always is positive, except for the EGARCH model, as this model mathematically ensures the output is positive.

\hypertarget{symmetric-normal-garch-model}{%
\subparagraph{Symmetric (normal) GARCH model}\label{symmetric-normal-garch-model}}

\noindent The standard GARCH model \autocite{bollerslev1986} is written consistent with \textcite{ghalanos2020} as in equation \eqref{eq:eq13} without external regressors.

\begin{align}
\sigma_t^2 = \beta_0  +  {\beta_1}\varepsilon _{t-1}^2 + {\beta_2}\sigma_{t-1}^2
 \label{eq:eq13}
\end{align}

\noindent where \(\sigma_t^2\) denotes the conditional variance, \(\beta_0\) the intercept and \(\varepsilon_t^2\) the residuals from the used mean process. The GARCH order is defined by \((q, p)\) (ARCH, GARCH), which is here \((1, 1)\). As \textcite{ghalanos2020} describes: "one of the key features of the observed behavior of financial data which GARCH models capture is volatility clustering which may be quantified in the persistence parameter \(\hat{P}\) specified as in equation \eqref{eq:eq14} for a GARCH model of order \((1,1)\).

\begin{align}
\hat{P} =  \beta_1  + \beta_2.
 \label{eq:eq14}
\end{align}

\noindent The unconditional variance of the standard GARCH model of Bollerslev is very similar to the ARCH model, but with the Garch parameter (\(\beta_2\)) included as in equation \eqref{eq:eq15}.

\begin{equation}
\begin{split}
\hat{\sigma}^2 
&= \dfrac{\beta_0}{1 - \hat{P}} \\
&= \dfrac{\beta_0}{1 - \beta_1 - \beta_2}
\end{split}
 \label{eq:eq15}
\end{equation}

\hypertarget{igarch-model}{%
\subparagraph{IGARCH model}\label{igarch-model}}

\noindent Following \textcite{ghalanos2020}, the integrated GARCH model \autocite{bollerslev1986} can also be estimated. This model assumes the persistence \(\hat{P} = 1\). This is done by Ghalanos, by setting the sum of the ARCH and GARCH parameters to 1. Because of this unit-persistence, the unconditional variance cannot be calculated.

\hypertarget{gjrgarch-model}{%
\subparagraph{GJRGARCH model}\label{gjrgarch-model}}

\noindent The GJRGARCH model \autocite{glosten1993}, which is an alternative for the asymmetric GARCH (AGARCH) by \textcite{engle1990} and \textcite{engle1993}, models both positive as negative shocks on the conditional variance asymmetrically by using an indicator variable \(I_t-1\), it is specified as in equation \eqref{eq:eq17}.

\begin{align}
\sigma_t^2 = \beta_0 + \beta_1 \varepsilon_{t-1}^2 + \gamma_j I_{t-1} \varepsilon_{t-1}^2 + \beta_2 \sigma_{t-1}^2
 \label{eq:eq17}
\end{align}

\noindent where \(\gamma_j\) represents the \emph{leverage} term. The indicator function \(I\) takes on value 1 for \(\varepsilon \le 0\), 0 otherwise. Because of the indicator function, persistence of the model now crucially depends on the asymmetry of the conditional distribution used according to \textcite{ghalanos2020}.

\hypertarget{egarch-model}{%
\subparagraph{EGARCH model}\label{egarch-model}}

\noindent The EGARCH model or exponential GARCH model \autocite{nelson1991} is defined as in equation \eqref{eq:eq16}. The advantage of the EGARCH model is that there are no parameter restrictions, since the output is log variance (which cannot be negative mathematically), instead of variance.

\begin{align}
\log_e(\sigma_t^2) = \beta_0 + \beta_1 z_{t-1} + \gamma_1 (|z_{t-1}| - E|z_{t-1}|)+ \beta_2 \log_e(\sigma_{t-1}^2)
 \label{eq:eq16}
\end{align}

\noindent where \(\beta_1\) captures the sign effect and \(\gamma_j\) the size effect.

\hypertarget{nagarch-model}{%
\subparagraph{NAGARCH model}\label{nagarch-model}}

\noindent The NAGARCH or nonlinear asymmetric model \autocite{engle1993}. It is specified as in equation \eqref{eq:eq18}. The model is \emph{asymmetric} as it allows for positive and negative shocks to differently affect conditional variance and \emph{nonlinear} because a large shock is not a linear transformation of a small shock.

\begin{align}
\sigma_t^2 = \beta_0 + \beta_1 (\varepsilon_{t-1}+ \gamma_1 \sqrt{\sigma_{t-1}})^2 + \beta_2 \sigma_{t-1}^2
 \label{eq:eq18}
\end{align}

As before, \(\gamma_1\) represents the \emph{leverage} term.

\hypertarget{tgarch-model}{%
\subparagraph{TGARCH model}\label{tgarch-model}}

\noindent The TGARCH or threshold model \autocite{zakoian1994} also models asymmetries in volatility depending on the sign of the shock, but contrary to the GJRGARCH model it uses the conditional standard deviation instead of conditional variance. It is specified as in \eqref{eq:eq19}.

\begin{align}
\sigma_t = \beta_0 + \beta_1^+ \varepsilon_{t-1}^+ - \beta_1^{-} \varepsilon_{t-1}^{-} + \beta_2 \sigma_{t-1}
 \label{eq:eq19}
\end{align}

\noindent where \(\varepsilon_{t-1}^+\) is equal to \(\varepsilon_{t-1}\) if the term is negative and equal to 0 if the term is positive. The reverse applies to \(\varepsilon_{t-1}^-\). They cite \textcite{davidian1987} who find that using volatility instead of variance as scaling input variable gives better variance estimates. This is due to absolute residuals (contrary to squared residuals with variance) more closely predicting variance for non-normal distributions.

\hypertarget{tsgarch-model}{%
\subparagraph{TSGARCH model}\label{tsgarch-model}}

\noindent The absolute value Garch model or TS-Garch model, as named after \textcite{taylor1986} and \textcite{schwert1989}, models the conditional standard deviation and is intuitively specified like a normal GARCH model, but with the absolute value of the shock term. It is specified as in \eqref{eq:eq20}.

\begin{align}
\sigma_t = \beta_0 + \beta_1 \left|\varepsilon_{t-1}\right| + \beta_2 \sigma_{t-1}
 \label{eq:eq20}
\end{align}

\hypertarget{ewma}{%
\subparagraph{EWMA}\label{ewma}}

\noindent An alternative to the series of GARCH models is the exponentially weighted moving average or EWMA model. This model calculates conditional variance based on the shocks from previous periods. The idea is that by including a smoothing parameter \(\lambda\) more weight is assigned to recent periods than distant periods. The \(\lambda\) must be less than 1. It is specified as in \eqref{eq:eq21}.

\begin{align}
\sigma_t^2 = (1-\lambda) \sum\limits_{j=1}^\infty (\lambda^j \varepsilon_{t-j}^2)
 \label{eq:eq21}
\end{align}

In practice a \(\lambda\) of 0.94 is often used, such as by the financial risk management company RiskMetrics\(^{TM}\) model of J.P. Morgan \autocite{morganguarantytrustcompany1996}.

\newpage

\hypertarget{appendix-to-findings}{%
\chapter{Appendix to findings}\label{appendix-to-findings}}

\hypertarget{goodness-of-fit}{%
\subsubsection{Goodness of fit}\label{goodness-of-fit}}

\noindent As already mentioned, next to testing the models in part \ref{analysis}, we also tested other models using the different distributions. This we did in order to check if distributions that capture the higher moment effects are really better in terms of goodness of fit. We did a small data mining experiment with 140 models that were estimated. This can ofcourse lead to overfitting because of the fit in-sample. However, we can decide if there is a trend using the different distributions for the several GARCH models. Thus, in this experiment, our rule of thumb was to examine general trends. Six cases were examined. ~\\

\newpage

First, in figure \ref{fig:aic1}, symmetric GARCH with symmetric distributions are looked at. As you can see the general error distribution (GED) seems to perform slightly better than the the T distribution. While the student's t distribution (T) performs better than the normal distribution (NORM) according to the AIC. Which is consistent with the literature that found that the assumption of the normal distribution is a rather poor assumption.

\begin{figure}[h]

{\centering \includegraphics[width=0.9\linewidth]{figures/aicfigures/symmetric aics} 

}

\caption{Goodness of fit symmetric GARCH and distributions}\label{fig:aic1}
\end{figure}
\clearpage
\newpage

\noindent Second, in figure \ref{fig:aic2}, symmetric GARCH models with the best symmetric distribution (T) and other distributions (SGED, ST) are looked at. As you can see the SGED seems to perform better than the skewed student's t distribution (ST) and the latter is better than the T distribution. This is consistent with \textcite{giot2003} that the skewed student's t (ST) distribution outperforms the symmetric distributions.

\begin{figure}[h]

{\centering \includegraphics[width=0.9\linewidth]{figures/aicfigures/symmetric aics2} 

}

\caption{Goodness of fit symmetric GARCH and other distributions}\label{fig:aic2}
\end{figure}
\clearpage
\newpage

\noindent In figure \ref{fig:aic3} you can see the same patter as in figure \ref{fig:aic1}, the student's t distribution performs best among the symmetric distributions.

\begin{figure}[h]

{\centering \includegraphics[width=0.9\linewidth]{figures/aicfigures/asymmetric aics} 

}

\caption{Goodness of fit asymmetric GARCH and symmetric distributions}\label{fig:aic3}
\end{figure}
\newpage
\clearpage

\noindent Then, in figure \ref{fig:aic4} the same patter arises as in figure \ref{fig:aic2}, the skewed student's t distribution again seems to be the most optimal one to use. Therefore the ST distribution is chosen as final model for the Euro Stoxx 50 index.

\begin{figure}[h]

{\centering \includegraphics[width=0.9\linewidth]{figures/aicfigures/asymmetric aics2} 

}

\caption{Goodness of fit asymmetric GARCH and symmetric distributions}\label{fig:aic4}
\end{figure}

\noindent In two additional figures the family garch models (TGARCH, NAGARCH and AVGARCH) are examined, the same patterns were observed as above\footnote{Although we have to note that for some models like TGARCH and AVGARCH with SGED distribution the AIC was double of other models and therefore these models seem to work very poorly or are mispecified.}.


%%%%% REFERENCES

% JEM: Quote for the top of references (just like a chapter quote if you're using them).  Comment to skip.
% \begin{savequote}[8cm]
% The first kind of intellectual and artistic personality belongs to the hedgehogs, the second to the foxes \dots
%   \qauthor{--- Sir Isaiah Berlin \cite{berlin_hedgehog_2013}}
% \end{savequote}

\setlength{\baselineskip}{0pt} % JEM: Single-space References

{\renewcommand*\MakeUppercase[1]{#1}%
\printbibliography[heading=bibintoc,title={\bibtitle}]}


\end{document}
